CREATE TABLE "blessings" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "blessings_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blessing_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"guest_id" text NOT NULL,
	"message" text NOT NULL,
	"photo_url" text,
	"status" text NOT NULL,
	"reject_reason" text,
	"wall_status" text
);
--> statement-breakpoint
CREATE TABLE "cake_box_assignments" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "cake_box_assignments_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cake_box_type_id" text NOT NULL,
	"guest_id" text NOT NULL,
	"assignment_rule" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cake_box_exclusions" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "cake_box_exclusions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text NOT NULL,
	"guest_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cake_box_extra_orders" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "cake_box_extra_orders_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"extra_order_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"cake_box_type_id" text NOT NULL,
	"quantity" integer NOT NULL,
	"recipient_name" text,
	"recipient_contact" text,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "cake_box_types" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "cake_box_types_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cake_box_type_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_default" boolean NOT NULL,
	"image_url" text,
	"price" integer
);
--> statement-breakpoint
CREATE TABLE "etiquette_settings" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"elder_near_main" boolean NOT NULL,
	"main_table_full" boolean NOT NULL,
	"same_category_together" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etiquette_warnings" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "etiquette_warnings_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"warning_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"warning_type" text NOT NULL,
	"message" text NOT NULL,
	"dismissed" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gift_items" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "gift_items_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gift_item_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"category" text NOT NULL,
	"description" text NOT NULL,
	"image_url" text,
	"unit_price" integer NOT NULL,
	"quantity" integer NOT NULL,
	"purchase_url" text,
	"distribution_time" text,
	"shipping_fee1" integer NOT NULL,
	"shipping_fee2" integer NOT NULL,
	"other_fee" integer NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "guest_categories" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "guest_categories_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "guest_categories_wedding_id_name_pk" PRIMARY KEY("wedding_id","name")
);
--> statement-breakpoint
CREATE TABLE "guests" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "guests_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guest_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"name" text NOT NULL,
	"side" text NOT NULL,
	"diet" text NOT NULL,
	"category" text NOT NULL,
	"contact" text NOT NULL,
	"child_chair_count" integer NOT NULL,
	"notes" text,
	"line_user_id" text,
	"rsvp_attending" text,
	"checked_in_at" text,
	"gift_amount" integer,
	"cake_box_distributed_type_id" text,
	"invitation_sent" boolean NOT NULL,
	"party_size" integer NOT NULL,
	"table_name" text,
	"deleted_at" text,
	"invitation_preference" text,
	"mailing_address" text,
	"blessing" text,
	"flower_drawing" text,
	"needs_shuttle" boolean,
	"shuttle_count" integer,
	"custom_answers" jsonb,
	"status" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "line_oas" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"oa_name" text NOT NULL,
	"channel_id" text NOT NULL,
	"add_friend_url" text
);
--> statement-breakpoint
CREATE TABLE "projection_settings" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"media_type" text NOT NULL,
	"photo_data_url" text,
	"video_url" text,
	"custom_flowers" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reception_accounts" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "reception_accounts_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"username" text NOT NULL,
	"password_hash" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rsvp_form_configs" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"theme" text NOT NULL,
	"banner" text,
	"questions" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rundown_items" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "rundown_items_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rundown_item_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"time" text,
	"duration_minutes" integer NOT NULL,
	"title" text NOT NULL,
	"location" text,
	"supplies" text,
	"note" text,
	"role_tasks" jsonb NOT NULL,
	"highlight" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rundown_roles" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "rundown_roles_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seating_tables" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "seating_tables_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"table_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"table_name" text NOT NULL,
	"capacity" integer NOT NULL,
	"position_x" double precision NOT NULL,
	"position_y" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seats" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "seats_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"table_id" text NOT NULL,
	"guest_id" text NOT NULL,
	"seat_number" integer NOT NULL,
	"seat_type" text NOT NULL,
	"party_index" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "thank_you_customizations" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "thank_you_customizations_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text NOT NULL,
	"guest_id" text NOT NULL,
	"custom_content" text NOT NULL,
	CONSTRAINT "thank_you_customizations_wedding_id_guest_id_pk" PRIMARY KEY("wedding_id","guest_id")
);
--> statement-breakpoint
CREATE TABLE "thank_you_templates" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"template_content" text NOT NULL,
	"template_image_url" text,
	"greeting" text,
	"signature" text,
	"signature_date" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "users_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"display_name" text NOT NULL,
	"role" text NOT NULL,
	"wedding_id" text,
	"deleted_at" text
);
--> statement-breakpoint
CREATE TABLE "venue_layouts" (
	"wedding_id" text PRIMARY KEY NOT NULL,
	"stage_width" double precision NOT NULL,
	"stage_height" double precision NOT NULL,
	"stage_position_x" double precision NOT NULL,
	"stage_position_y" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venue_markers" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_markers_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"marker_id" text PRIMARY KEY NOT NULL,
	"wedding_id" text NOT NULL,
	"label" text NOT NULL,
	"position_x" double precision NOT NULL,
	"position_y" double precision NOT NULL,
	"width" double precision NOT NULL,
	"height" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weddings" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "weddings_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"venue" text NOT NULL,
	"address" text NOT NULL,
	"date" text NOT NULL,
	"groom_name" text,
	"bride_name" text,
	"map_link" text,
	"parking_info" text,
	"transport_info" text,
	"transport_image_urls" jsonb,
	"owner_id" text,
	"deleted_at" text
);
--> statement-breakpoint
CREATE INDEX "blessings_wedding_id_index" ON "blessings" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "cake_box_assignments_guest_id_index" ON "cake_box_assignments" USING btree ("guest_id");--> statement-breakpoint
CREATE INDEX "cake_box_exclusions_wedding_id_index" ON "cake_box_exclusions" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "cake_box_extra_orders_wedding_id_index" ON "cake_box_extra_orders" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "cake_box_types_wedding_id_index" ON "cake_box_types" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "etiquette_warnings_wedding_id_index" ON "etiquette_warnings" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "gift_items_wedding_id_index" ON "gift_items" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "guests_wedding_id_index" ON "guests" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "reception_accounts_wedding_id_index" ON "reception_accounts" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "rundown_items_wedding_id_index" ON "rundown_items" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "rundown_roles_wedding_id_index" ON "rundown_roles" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "seating_tables_wedding_id_index" ON "seating_tables" USING btree ("wedding_id");--> statement-breakpoint
CREATE INDEX "seats_table_id_index" ON "seats" USING btree ("table_id");--> statement-breakpoint
CREATE INDEX "seats_guest_id_index" ON "seats" USING btree ("guest_id");--> statement-breakpoint
CREATE INDEX "venue_markers_wedding_id_index" ON "venue_markers" USING btree ("wedding_id");