CREATE TABLE "thank_you_batch_sends" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "thank_you_batch_sends_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text NOT NULL,
	"success_count" integer NOT NULL,
	"failed_count" integer NOT NULL,
	"sent_at" text NOT NULL,
	"sent_by" text NOT NULL
);
--> statement-breakpoint
CREATE INDEX "thank_you_batch_sends_wedding_id_index" ON "thank_you_batch_sends" USING btree ("wedding_id");