CREATE TABLE "gift_categories" (
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "gift_categories_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wedding_id" text NOT NULL,
	"category_id" text NOT NULL,
	"name" text NOT NULL,
	"sort_order" integer NOT NULL,
	CONSTRAINT "gift_categories_wedding_id_category_id_pk" PRIMARY KEY("wedding_id","category_id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "gift_categories_wedding_id_name_index" ON "gift_categories" USING btree ("wedding_id","name");--> statement-breakpoint
--> 既有婚禮回填預設六類（issue #124）：gift_items.category 既存值即為 slug，categoryId 沿用同一組 slug
--> 即可對上、品項資料免搬移；新婚禮的預設類改由建立婚禮的 handler 寫入
INSERT INTO "gift_categories" ("wedding_id", "category_id", "name", "sort_order")
SELECT w."wedding_id", c."category_id", c."name", c."sort_order"
FROM "weddings" w
CROSS JOIN (VALUES
	('table', '桌上禮', 1),
	('second_entrance', '二進禮', 2),
	('game', '遊戲禮', 3),
	('send_off', '送客禮', 4),
	('room_visit', '探房禮', 5),
	('tea_ceremony', '喝茶禮', 6)
) AS c("category_id", "name", "sort_order");