// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/rsvp/[guestId].vue（與新人關係 / 出席細節 / 接駁車 / 喜帖 條件渲染）
// Pattern: conditional-render

import { expect, test } from '@playwright/test'

import { resetMockData } from '../helpers'

// 訪客 RSVP 為公開頁（不需登入）；以語意 anchor 定位，不依賴新人實際姓名
const RSVP_URL = '/rsvp/guest-001?weddingId=wedding-001'

test.describe('vibe：訪客 RSVP 條件渲染', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
  })

  test('選新人側別後出現身分類別（家人/朋友/同事/其他）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 初始：尚未選側別 → 身分類別不顯示
    await expect(page.getByRole('button', { name: /^家人$/ })).toBeHidden()

    // 選任一側別（第一顆＝新郎側）
    await page.getByRole('button', { name: /的親友/ }).first().click()

    // 身分類別出現
    await expect(page.getByRole('button', { name: /^家人$/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^同事$/ })).toBeVisible()
  })

  test('切換是否出席 → 顯示/隱藏出席細節（餐點）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 預設出席 → 餐點區塊可見
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeVisible()

    // 改為不出席 → 出席細節隱藏
    await page.getByRole('button', { name: /^不出席$/ }).click()
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeHidden()

    // 改回出席 → 出席細節再現
    await page.getByRole('button', { name: /^出席$/ }).click()
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeVisible()
  })

  // 接駁題為系統題並帶顯示對象（預設範本 audience='groom'）：只有男方親友看得到
  test('接駁題依顯示對象條件渲染（未選側別隱藏 → 男方出現 → 女方消失）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 初始：尚未選側別 → 限男方的接駁題不顯示
    await expect(page.getByText(/高雄地區接駁車/)).toBeHidden()

    // 選男方 → 接駁題出現，並帶後台設定的補充說明
    await page.getByRole('button', { name: /的親友/ }).first().click()
    await expect(page.getByText(/高雄地區接駁車/)).toBeVisible()
    await expect(page.getByText(/只有高雄地區的家人/)).toBeVisible()

    // 可選「需要搭乘」，並出現搭車人數 stepper
    await page.getByRole('button', { name: /需要搭乘/ }).click()
    await expect(page.getByTestId('rsvp-shuttle-count')).toBeVisible()

    // 改選女方 → 接駁題消失
    await page.getByRole('button', { name: /的親友/ }).nth(1).click()
    await expect(page.getByText(/高雄地區接駁車/)).toBeHidden()
  })

  test('喜帖類型切換 → 顯示對應條件欄位（電子＝加 LINE、實體＝地址）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 電子喜帖 → 出現加 LINE 區塊（行動以連結呈現，改以說明文字斷言）
    await page.getByRole('button', { name: /電子喜帖/ }).click()
    await expect(page.getByText(/電子喜帖將透過 LINE 寄送/)).toBeVisible()

    // 實體喜帖 → 出現寄送地址欄
    await page.getByRole('button', { name: /實體喜帖/ }).click()
    await expect(page.getByText(/紙本喜帖寄送地址/)).toBeVisible()
  })
})
