// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/seating.vue（空位 @click tap 入座 + 待放置提示列）
//              app/components/seating/SeatingGuestSidebar.vue（側欄賓客點選待放置）
//              app/components/common/ConfirmModal.vue（extra slot：移至其他座位）
// Pattern: tap-to-assign（互動：點選待放置 → 點座位 commit；issue #73 觸控備援）

import { expect, test } from '@playwright/test'

import {
  login,
  resetMockData,
  TestUsers,
  waitForApiCall,
} from '../helpers'

// 觸控排位備援（issue #73）：手機/平板無 HTML5 drag events，
// 以「點選賓客 → 待放置 → 點桌上空位」完成入座；換位走取消座位視窗的「移至其他座位」。
// 以 hasTouch + tap() 模擬觸控裝置，並驗證桌機拖曳行為不變（兩路徑並存）。

const SEATING_URL = '/weddings/wedding-001/seating'

test.use({ hasTouch: true })

test.beforeEach(async ({ page }) => {
  await resetMockData(page)
  await login(page, TestUsers.admin.account, TestUsers.admin.password)
})

test.describe('vibe：tap-to-assign 觸控排位備援', () => {
  test('觸控入座：點選側欄賓客進入待放置（再點取消）、點空位完成入座', async ({ page }) => {
    await page.goto(SEATING_URL, { waitUntil: 'networkidle' })

    // 點選賓客 → 進入待放置（提示列出現並可識別賓客）
    await page.getByTestId('vibe-seating-guest-guest-001').tap()
    await expect(page.getByTestId('vibe-seating-pending-bar')).toBeVisible()
    await expect(page.getByTestId('vibe-seating-pending-bar')).toContainText('陳大明')

    // 再點同一位 → 取消待放置
    await page.getByTestId('vibe-seating-guest-guest-001').tap()
    await expect(page.getByTestId('vibe-seating-pending-bar')).not.toBeVisible()

    // 重新選取 → 點 table-002 空位 1 完成入座
    await page.getByTestId('vibe-seating-guest-guest-001').tap()
    const apiCall = waitForApiCall(page, /\/tables\/table-002\/seats(\?|$)/, 'POST')
    await page.getByTestId('table-002-empty-1').tap()
    const request = await apiCall
    expect(request.postDataJSON()).toMatchObject({ guestId: 'guest-001', seatNumber: 1 })

    // 入座後：待放置解除、賓客顯示於該桌
    await expect(page.getByTestId('vibe-seating-pending-bar')).not.toBeVisible()
    await expect(page.getByRole('article', { name: '男方家屬桌' }).getByText(/陳大明/).first()).toBeVisible()
  })

  test('提示列「取消」按鈕可解除待放置', async ({ page }) => {
    await page.goto(SEATING_URL, { waitUntil: 'networkidle' })

    await page.getByTestId('vibe-seating-guest-guest-001').tap()
    await expect(page.getByTestId('vibe-seating-pending-bar')).toBeVisible()

    await page.getByTestId('vibe-seating-pending-cancel').tap()
    await expect(page.getByTestId('vibe-seating-pending-bar')).not.toBeVisible()
  })

  test('觸控換位：點座上賓客 → 移至其他座位 → 點他桌空位完成單席移動', async ({ page }) => {
    // Given：guest-001 已入座 table-002
    const seat = await page.request.post(
      '/api/v1/weddings/wedding-001/tables/table-002/seats',
      { data: { guestId: 'guest-001', seatNumber: 1 } },
    )
    expect(seat.ok()).toBeTruthy()
    await page.goto(SEATING_URL, { waitUntil: 'networkidle' })

    // 點座上賓客（accessible name 語意不變：取消座位 X）→ 確認框多了換位入口
    await page.getByRole('article', { name: '男方家屬桌' }).getByRole('button', { name: /取消座位/ }).first().tap()
    await page.getByTestId('vibe-seat-move').tap()
    await expect(page.getByTestId('vibe-seating-pending-bar')).toBeVisible()

    // 點 table-003 空位 → 送出單席移動
    const moveCall = waitForApiCall(page, /\/seats\/move(\?|$)/, 'POST')
    await page.getByTestId('table-003-empty-2').tap()
    await moveCall
    await expect(page.getByRole('article', { name: '女方家屬桌' }).getByText(/陳大明/).first()).toBeVisible()
  })

  test('觸控取消座位：點座上賓客 → 確認取消（既有路徑在觸控可用）', async ({ page }) => {
    const seat = await page.request.post(
      '/api/v1/weddings/wedding-001/tables/table-002/seats',
      { data: { guestId: 'guest-001', seatNumber: 1 } },
    )
    expect(seat.ok()).toBeTruthy()
    await page.goto(SEATING_URL, { waitUntil: 'networkidle' })

    const apiCall = waitForApiCall(page, /\/tables\/table-002\/seats\/guest-001(\?|$)/, 'DELETE')
    await page.getByRole('article', { name: '男方家屬桌' }).getByRole('button', { name: /取消座位/ }).first().tap()
    await page.getByTestId('confirm-ok').tap()
    await apiCall
    await expect(page.getByRole('article', { name: '男方家屬桌' }).getByText(/陳大明/)).not.toBeVisible()
  })

  test('桌機拖曳行為不變：側欄拖曳到空位仍可入座（與 tap 並存）', async ({ page }) => {
    await page.goto(SEATING_URL, { waitUntil: 'networkidle' })

    const guest = page.getByTestId('vibe-seating-guest-guest-001')
    const slot = page.getByTestId('table-002-empty-1')
    const apiCall = waitForApiCall(page, /\/tables\/table-002\/seats(\?|$)/, 'POST')
    await guest.dragTo(slot)
    const request = await apiCall
    expect(request.postDataJSON()).toMatchObject({ guestId: 'guest-001', seatNumber: 1 })
    await expect(page.getByRole('article', { name: '男方家屬桌' }).getByText(/陳大明/).first()).toBeVisible()
  })
})
