// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/rsvp.vue（刪除賓客 / 編輯回覆 / 條件欄位）
// Pattern: confirm-delete / interaction / conditional-render

import { expect, test } from '@playwright/test'

import { findEntity, login, resetMockData, TestUsers } from '../helpers'

const RSVP_ADMIN_URL = '/weddings/wedding-001/rsvp'

test.describe('vibe：後台 RSVP 編輯與刪除', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
    await page.goto(RSVP_ADMIN_URL, { waitUntil: 'networkidle' })
  })

  test('刪除賓客 → 確認後從清單消失', async ({ page }) => {
    // 確認目標賓客在列
    await expect(page.getByRole('row', { name: /陳大明/ })).toHaveCount(1)

    // 列上點「刪除」→ ConfirmModal → 確認（confirm-ok 為合約白名單 testid）
    await findEntity(page, /陳大明/)
      .getByRole('button', { name: /刪除/ })
      .click()
    // confirm-ok / confirm-cancel 為合約白名單 testid
    await expect(page.getByTestId('confirm-ok')).toBeVisible()
    await page.getByTestId('confirm-ok').click()

    // 該賓客從清單移除
    await expect(page.getByRole('row', { name: /陳大明/ })).toHaveCount(0)
  })

  test('編輯回覆 → 修改聯繫電話並儲存後，詳情顯示新值', async ({ page }) => {
    // 開啟王志強的「覆寫／編輯回覆」
    await findEntity(page, /王志強/)
      .getByRole('button', { name: /覆寫/ })
      .click()

    // 改聯繫電話（UInput，以 label 定位，避開 select 下拉）
    await page.getByLabel('聯繫電話').fill('0900111222')
    await page.getByRole('button', { name: /送出/ }).click()

    // modal 關閉（送出鈕消失）
    await expect(page.getByRole('button', { name: /送出/ })).toBeHidden()

    // 重開詳情 → 顯示新電話
    await findEntity(page, /王志強/)
      .getByRole('button', { name: /查看.*回覆/ })
      .click()
    await expect(page.getByText(/0900111222/)).toBeVisible()
  })

  test('編輯回覆 — 搭車人數依接駁需求條件顯示（用 seed 預填，不碰下拉）', async ({ page }) => {
    // 王志強（guest-003）seed needsShuttle=true → 搭車人數欄位顯示
    await findEntity(page, /王志強/)
      .getByRole('button', { name: /覆寫/ })
      .click()
    await expect(page.getByLabel('搭車人數')).toBeVisible()
    await page.getByRole('button', { name: /取消/ }).click()
    await expect(page.getByRole('button', { name: /送出/ })).toBeHidden()

    // 陳大明（未填接駁）→ 搭車人數欄位不顯示
    await findEntity(page, /陳大明/)
      .getByRole('button', { name: /覆寫/ })
      .click()
    await expect(page.getByLabel('搭車人數')).toBeHidden()
  })
})
