// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/rsvp.vue（下載 Excel / 下載花朵 ZIP / 單張花朵 PNG）
// Pattern: interaction（以 download-event 斷言檔名）

import { expect, test } from '@playwright/test'

import { findEntity, login, resetMockData, TestUsers } from '../helpers'

const RSVP_ADMIN_URL = '/weddings/wedding-001/rsvp'

test.describe('vibe：後台 RSVP 下載', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
    await page.goto(RSVP_ADMIN_URL, { waitUntil: 'networkidle' })
  })

  test('下載 Excel → 觸發 CSV 下載', async ({ page }) => {
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.getByRole('button', { name: /下載 Excel/ }).click(),
    ])
    expect(download.suggestedFilename()).toMatch(/RSVP.*\.csv$/)
  })

  test('下載花朵 ZIP → 觸發 zip 下載（seed 已有手繪小花）', async ({ page }) => {
    const trigger = page.getByRole('button', { name: /下載花朵/ })
    await expect(trigger).toBeEnabled()
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      trigger.click(),
    ])
    expect(download.suggestedFilename()).toMatch(/flowers.*\.zip$/)
  })

  test('詳情單張花朵 → 下載 PNG', async ({ page }) => {
    // 王志強（guest-003）seed 已有手繪小花
    await findEntity(page, /王志強/)
      .getByRole('button', { name: /查看.*回覆/ })
      .click()
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.getByRole('button', { name: /下載 PNG/ }).click(),
    ])
    expect(download.suggestedFilename()).toMatch(/flower.*\.png$/)
  })
})
