// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/rsvp/[guestId].vue（與新人關係 / 出席細節 / 接駁車 / 喜帖 條件渲染）
// Pattern: conditional-render

import { expect, test } from '@playwright/test'

import { resetMockData } from '../helpers'

// 訪客 RSVP 為公開頁（不需登入）；以語意 anchor 定位，不依賴新人實際姓名
const RSVP_URL = '/rsvp/guest-001?weddingId=wedding-001'

test.describe('vibe：訪客 RSVP 條件渲染', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
  })

  test('選新人側別後出現身分類別（家人/朋友/同事/其他）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 初始：尚未選側別 → 身分類別不顯示
    await expect(page.getByRole('button', { name: /^家人$/ })).toBeHidden()

    // 選任一側別（第一顆＝新郎側）
    await page.getByRole('button', { name: /的親友/ }).first().click()

    // 身分類別出現
    await expect(page.getByRole('button', { name: /^家人$/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^同事$/ })).toBeVisible()
  })

  test('切換是否出席 → 顯示/隱藏出席細節（餐點）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 預設出席 → 餐點區塊可見
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeVisible()

    // 改為不出席 → 出席細節隱藏
    await page.getByRole('button', { name: /^不出席$/ }).click()
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeHidden()

    // 改回出席 → 出席細節再現
    await page.getByRole('button', { name: /^出席$/ }).click()
    await expect(page.getByRole('button', { name: /^葷食$/ })).toBeVisible()
  })

  test('男方親友＋出席 → 顯示接駁車；選需要搭乘 → 顯示搭車人數', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 選新郎側（第一顆）；預設為出席 → 接駁車提問出現
    await page.getByRole('button', { name: /的親友/ }).first().click()
    await expect(page.getByText(/高雄地區接駁車/)).toBeVisible()

    // 選「需要搭乘」→ 搭車人數欄位出現
    await page.getByRole('button', { name: /需要搭乘/ }).click()
    await expect(page.getByText(/搭車人數/)).toBeVisible()
  })

  test('喜帖類型切換 → 顯示對應條件欄位（電子＝加 LINE、實體＝地址）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    // 電子喜帖 → 出現加 LINE 區塊（行動以連結呈現，改以說明文字斷言）
    await page.getByRole('button', { name: /電子喜帖/ }).click()
    await expect(page.getByText(/電子喜帖將透過 LINE 寄送/)).toBeVisible()

    // 實體喜帖 → 出現寄送地址欄
    await page.getByRole('button', { name: /實體喜帖/ }).click()
    await expect(page.getByText(/紙本喜帖寄送地址/)).toBeVisible()
  })
})
