// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/rsvp/[guestId].vue（stepper 加減 / 祝福快速帶入 / 小花橡皮擦）
// Pattern: interaction

import { expect, test } from '@playwright/test'

import { resetMockData } from '../helpers'

const RSVP_URL = '/rsvp/guest-001?weddingId=wedding-001'

test.describe('vibe：訪客 RSVP 互動', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
  })

  test('攜伴人數 stepper 加減（以具名欄位讀值，上限 10）', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    const field = page.getByLabel(/攜伴人數/)
    await expect(field).toHaveValue('0')

    // 多一位 → 1
    await page.getByRole('button', { name: /多一位/ }).click()
    await expect(field).toHaveValue('1')

    // 少一位 → 0
    await page.getByRole('button', { name: /少一位/ }).click()
    await expect(field).toHaveValue('0')
  })

  test('祝福快速帶入 → 點祝賀語填入留言框', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    const textarea = page.getByPlaceholder(/寫下您想對新人說的話/)
    await expect(textarea).toHaveValue('')

    await page.getByRole('button', { name: /新婚快樂/ }).click()
    await expect(textarea).toHaveValue(/新婚快樂/)
  })

  test('小花橡皮擦切換 → aria-pressed 反映啟用狀態', async ({ page }) => {
    await page.goto(RSVP_URL, { waitUntil: 'networkidle' })

    const eraser = page.getByRole('button', { name: /橡皮擦/ })
    await expect(eraser).toHaveAttribute('aria-pressed', 'false')

    await eraser.click()
    await expect(eraser).toHaveAttribute('aria-pressed', 'true')
  })

  // canvas 繪製後「清除」由 disabled → enabled 需模擬指標繪圖，時序/座標較脆弱，
  // 不在自動 vibe 範圍；保留待人工或日後補強。
  test.skip('小花繪製後「清除」變為可用 — 待補', async () => {
    // TODO: 以 page.mouse 在 rsvp-flower-canvas 範圍繪製後，斷言「清除」按鈕 enabled
    // Source hunk: app/pages/rsvp/[guestId].vue（canvas pointer 繪圖）
  })
})
