// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/thank-you.vue（範本 / 客製 inline 編輯切換）
// Pattern: toggle

import { expect, test } from '@playwright/test'

import { login, resetMockData, TestUsers } from '../helpers'

const THANKYOU_URL = '/weddings/wedding-001/thank-you'

test.describe('vibe：謝卡 inline 編輯切換', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
  })

  test('範本：點「編輯謝卡範本」展開編輯欄、取消收起', async ({ page }) => {
    await page.goto(THANKYOU_URL, { waitUntil: 'networkidle' })

    // placeholder 為穩定語意錨點（避開孤兒 testid）
    const contentField = page.getByPlaceholder('請輸入謝卡範本內容')
    await expect(contentField).toBeHidden() // 初始摺疊

    await page.getByRole('button', { name: /編輯謝卡範本/ }).click()
    await expect(contentField).toBeVisible() // 展開

    await page.getByRole('button', { name: /^取消$/ }).click()
    await expect(contentField).toBeHidden() // 收起
  })

  test('客製：點「客製謝卡」展開編輯欄、取消收起', async ({ page }) => {
    await page.goto(THANKYOU_URL, { waitUntil: 'networkidle' })

    const customField = page.getByPlaceholder('請輸入客製謝卡內容')
    await expect(customField).toBeHidden()

    await page.getByRole('button', { name: /客製謝卡/ }).click()
    await expect(customField).toBeVisible()

    await page.getByRole('button', { name: /^取消$/ }).click()
    await expect(customField).toBeHidden()
  })
})
