// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/rsvp.vue（查看回覆詳情 Modal）
// Pattern: modal-toggle

import { expect, test } from '@playwright/test'

import { login, resetMockData, TestUsers } from '../helpers'

const RSVP_ADMIN_URL = '/weddings/wedding-001/rsvp'

test.describe('vibe：後台 RSVP 查看回覆詳情', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
  })

  test('點「查看回覆」開啟詳情、按關閉收起', async ({ page }) => {
    await page.goto(RSVP_ADMIN_URL, { waitUntil: 'networkidle' })

    // 開啟某賓客的回覆詳情（按鈕 aria-label 為「查看 {姓名} 的回覆」）
    await page.getByRole('button', { name: /查看.*回覆/ }).first().click()

    // 詳情內容出現（標題「…的回覆」與關係欄位）
    await expect(page.getByText(/的回覆/)).toBeVisible()
    await expect(page.getByText(/與新人關係/)).toBeVisible()
    await expect(page.getByText(/聯繫電話/)).toBeVisible()

    // 關閉 → 詳情收起
    await page.getByRole('button', { name: /關閉/ }).click()
    await expect(page.getByText(/與新人關係/)).toBeHidden()
  })
})
