// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/thank-you.vue（客製清單空狀態）
// Pattern: empty-state

import { expect, test } from '@playwright/test'

import { login, resetMockData, TestUsers } from '../helpers'

const THANKYOU_URL = '/weddings/wedding-001/thank-you'

test.describe('vibe：謝卡客製空狀態', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
  })

  test('客製清單預設為空 → 顯示「尚無客製謝卡」', async ({ page }) => {
    await page.goto(THANKYOU_URL, { waitUntil: 'networkidle' })
    await expect(page.getByText(/尚無客製謝卡/)).toBeVisible()
  })
})
