// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/rsvp.vue（賓客回覆摘要欄位 + 詳情條件列）
// Pattern: new-region / conditional-render

import { expect, test } from '@playwright/test'

import { findEntity, login, resetMockData, TestUsers } from '../helpers'

const RSVP_ADMIN_URL = '/weddings/wedding-001/rsvp'

test.describe('vibe：後台 RSVP 回覆摘要', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
    await page.goto(RSVP_ADMIN_URL, { waitUntil: 'networkidle' })
  })

  test('已回覆者顯示摘要、未回覆者欄位以「-」呈現', async ({ page }) => {
    // 王志強（guest-003）已回覆：男方 / 電子喜帖 / 接駁 2 位
    const replied = findEntity(page, /王志強/)
    await expect(replied).toContainText(/男方/)
    await expect(replied).toContainText(/電子/)
    await expect(replied).toContainText(/2 位/)

    // 陳大明（guest-001）未提交：摘要欄位以「-」呈現
    const pending = findEntity(page, /陳大明/)
    await expect(pending).toContainText(/未提交/)
    await expect(pending).toContainText('-')
  })

  test('詳情顯示祝福與手繪小花（已填者）', async ({ page }) => {
    await findEntity(page, /王志強/)
      .getByRole('button', { name: /查看.*回覆/ })
      .click()
    await expect(page.getByText(/祝福留言/)).toBeVisible()
    await expect(page.getByRole('img', { name: /手繪小花/ })).toBeVisible()
  })

  test('未填欄位不顯示對應詳情列', async ({ page }) => {
    await findEntity(page, /陳大明/)
      .getByRole('button', { name: /查看.*回覆/ })
      .click()
    // guest-001 無祝福、無小花 → 不顯示這些列
    await expect(page.getByText(/祝福留言/)).toBeHidden()
    await expect(page.getByRole('img', { name: /手繪小花/ })).toBeHidden()
  })
})
