// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/weddings/[weddingId]/index.vue（新人姓名顯示區）
// Pattern: new-region

import { expect, test } from '@playwright/test'

import { login, resetMockData, TestUsers } from '../helpers'

const WEDDING_URL = '/weddings/wedding-001'

test.describe('vibe：婚禮資訊新人姓名區', () => {
  test.beforeEach(async ({ page }) => {
    await resetMockData(page)
    await login(page, TestUsers.admin.account, TestUsers.admin.password)
  })

  test('顯示新人姓名區（志明 & 春嬌，單一節點）', async ({ page }) => {
    await page.goto(WEDDING_URL, { waitUntil: 'networkidle' })
    // 「新人姓名」標籤存在
    await expect(page.getByText('新人姓名')).toBeVisible()
    // 顯示區以單一節點呈現「{groom} & {bride}」（seed：志明 & 春嬌）
    await expect(page.getByText(/志明[^\n\r&\u2028\u2029]*&.*春嬌/).first()).toBeVisible()
  })
})
