# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 新增喜餅款式
  管理員新增喜餅款式

  @happy-path @happy-path
  Rule: 成功新增喜餅款式
    管理員成功新增一個喜餅款式

    Scenario: 成功新增喜餅款式
      管理員新增一個喜餅款式
      Given no prior events
      When Admin sends AddCakeBoxType on stream "cakeboxtype-001":
        """
        {
          "name": "經典禮盒",
          "isDefault": true,
          "weddingId": "wedding-001",
          "description": "傳統經典喜餅禮盒"
        }
        """
      Then the CakeBoxTypeAdded event is emitted with:
        """
        {
          "name": "經典禮盒",
          "isDefault": true,
          "weddingId": "wedding-001",
          "description": "傳統經典喜餅禮盒"
        }
        """
