# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 新增賓客
  管理員手動新增一位賓客

  @happy-path @happy-path
  Rule: 成功新增賓客
    管理員填寫完整賓客資料後成功新增

    Scenario: 成功新增賓客
      管理員新增一位男方賓客
      Given no prior events
      When Admin sends AddGuest on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "需要靠近舞台",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      Then the GuestAdded event is emitted with:
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "需要靠近舞台",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
