# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 新增桌次
  管理員在場地平面圖上新增桌次

  @happy-path @happy-path
  Rule: 成功新增桌次
    提供完整桌次資訊後成功新增

    Scenario: 成功新增桌次
      管理員提供桌次名稱、座位數、位置後成功新增
      Given no prior events
      When Admin sends AddTable on stream "table-001":
        """
        {
          "tableId": "table-001",
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      Then the TableAdded event is emitted with:
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
