# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 審核通過祝福
  管理員審核通過賓客提交的祝福留言

  @happy-path @happy-path
  Rule: 成功審核通過祝福
    已提交的祝福成功通過審核

    Scenario: 成功審核通過祝福
      管理員審核通過已提交的祝福
      Given the BlessingSubmitted event has occurred on stream "blessing-001":
        """
        {
          "guestId": "guest-001",
          "message": "祝福新人百年好合！",
          "photoUrl": "https://example.com/photo.jpg",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends ApproveBlessing on stream "blessing-001":
        """
        {}
        """
      Then the BlessingApproved event is emitted with:
        """
        {
          "approvedBy": "admin-001"
        }
        """

  @not-found @blessing-not-found
  Rule: 祝福不存在
    審核不存在的祝福時回傳錯誤

    Scenario: 祝福不存在
      嘗試審核不存在的祝福
      Given no prior events
      When Admin sends ApproveBlessing on stream "blessing-999":
        """
        {}
        """
      Then the operation fails with: 祝福不存在

  @condition @already-reviewed
  Rule: 祝福已審核
    已審核過的祝福不可再次審核

    Scenario: 祝福已審核通過
      嘗試對已審核通過的祝福再次通過
      Given the BlessingSubmitted event has occurred on stream "blessing-001":
        """
        {
          "guestId": "guest-001",
          "message": "祝福新人百年好合！",
          "photoUrl": "https://example.com/photo.jpg",
          "weddingId": "wedding-001"
        }
        """
      And the BlessingApproved event has occurred on stream "blessing-001":
        """
        {
          "approvedBy": "admin-001"
        }
        """
      When Admin sends ApproveBlessing on stream "blessing-001":
        """
        {}
        """
      Then the operation fails with: 祝福已審核
