# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 綁定賓客 LINE
  賓客透過專屬連結綁定 LINE userId

  @happy-path @happy-path
  Rule: 成功綁定 LINE
    賓客成功綁定 LINE userId

    Scenario: 成功綁定 LINE
      賓客透過專屬連結綁定 LINE
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Guest sends BindGuestLine on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "lineUserId": "U1234567890abcdef"
        }
        """
      Then the GuestLineBound event is emitted with:
        """
        {
          "weddingId": "wedding-001",
          "lineUserId": "U1234567890abcdef"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    綁定不存在的賓客時回傳錯誤

    Scenario: 賓客不存在
      綁定尚未新增的賓客
      Given no prior events
      When Guest sends BindGuestLine on stream "guest-999":
        """
        {
          "weddingId": "wedding-001",
          "lineUserId": "U9999999999"
        }
        """
      Then the operation fails with: 賓客不存在

  @condition @already-bound
  Rule: 已綁定 LINE
    賓客已綁定 LINE 時再次嘗試綁定回傳錯誤

    Scenario: 已綁定 LINE
      賓客已綁定 LINE，再次綁定失敗
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the GuestLineBound event has occurred on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "lineUserId": "U1234567890abcdef"
        }
        """
      When Guest sends BindGuestLine on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "lineUserId": "U9876543210fedcba"
        }
        """
      Then the operation fails with: 已綁定 LINE
