# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 接待報到
  接待人員在接待端為賓客完成報到

  @happy-path @happy-path
  Rule: 成功接待報到
    接待人員成功為賓客完成報到

    Scenario: 成功接待報到
      接待人員為賓客完成報到
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Receptionist sends CheckInByReception on stream "guest-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the GuestCheckedInByReception event is emitted with:
        """
        {
          "weddingId": "wedding-001",
          "checkedInAt": "2026-06-19T10:30:00.000Z",
          "checkedInBy": "receptionist-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    接待報到時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Receptionist sends CheckInByReception on stream "guest-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 賓客不存在

  @condition @already-checked-in
  Rule: 已報到
    賓客已完成報到不可重複報到

    Scenario: 已報到
      賓客已完成報到
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the GuestCheckedInByReception event has occurred on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "checkedInAt": "2026-06-19T10:00:00.000Z",
          "checkedInBy": "receptionist-001"
        }
        """
      When Receptionist sends CheckInByReception on stream "guest-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 賓客已報到
