# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 設定場地佈局
  管理員設定場地佈局（舞台位置與大小）

  @happy-path @happy-path
  Rule: 成功設定場地佈局
    婚禮已存在時成功設定

    Scenario: 成功設定場地佈局
      婚禮已建立，管理員設定舞台位置與大小
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
      When Admin sends ConfigureVenueLayout on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001",
          "stageWidth": 300,
          "stageHeight": 150,
          "stagePositionX": 500,
          "stagePositionY": 100
        }
        """
      Then the VenueLayoutConfigured event is emitted with:
        """
        {
          "stageWidth": 300,
          "stageHeight": 150,
          "stagePositionX": 500,
          "stagePositionY": 100
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時回傳錯誤

    Scenario: 婚禮不存在
      嘗試對不存在的婚禮設定場地佈局
      Given no prior events
      When Admin sends ConfigureVenueLayout on stream "wedding-999":
        """
        {
          "weddingId": "wedding-999",
          "stageWidth": 300,
          "stageHeight": 150,
          "stagePositionX": 500,
          "stagePositionY": 100
        }
        """
      Then the operation fails with: 婚禮不存在
