# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 設定喜餅指派
  管理員設定賓客或身分對應的喜餅款式指派規則

  @happy-path @happy-path
  Rule: 成功設定喜餅指派
    既有款式成功設定指派規則

    Scenario: 成功設定喜餅指派
      管理員設定喜餅指派規則
      Given the CakeBoxTypeAdded event has occurred on stream "cakeboxtype-001":
        """
        {
          "name": "經典禮盒",
          "isDefault": true,
          "weddingId": "wedding-001",
          "description": "傳統經典喜餅禮盒"
        }
        """
      When Admin sends ConfigureCakeBoxAssignment on stream "cakeboxtype-001":
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "assignmentRule": "家人→大餅＋豪華禮盒"
        }
        """
      Then the CakeBoxAssignmentConfigured event is emitted with:
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "assignmentRule": "家人→大餅＋豪華禮盒"
        }
        """

  @not-found @cake-box-type-not-found
  Rule: 喜餅款式不存在
    設定指派時喜餅款式不存在

    Scenario: 喜餅款式不存在
      嘗試對不存在的喜餅款式設定指派
      Given no prior events
      When Admin sends ConfigureCakeBoxAssignment on stream "cakeboxtype-999":
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "assignmentRule": "家人→大餅＋豪華禮盒"
        }
        """
      Then the operation fails with: 喜餅款式不存在
