# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 連結 LINE 官方帳號
  管理員將 LINE 官方帳號連結至婚禮

  @happy-path @happy-path
  Rule: 成功連結 LINE 官方帳號
    婚禮已存在時成功連結

    Scenario: 成功連結 LINE 官方帳號
      婚禮已建立，管理員連結 LINE 官方帳號
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
      When Admin sends ConnectLineOa on stream "wedding-001":
        """
        {
          "oaName": "王李婚禮小助手",
          "channelId": "1234567890",
          "weddingId": "wedding-001"
        }
        """
      Then the LineOaConnected event is emitted with:
        """
        {
          "oaName": "王李婚禮小助手",
          "channelId": "1234567890"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時回傳錯誤

    Scenario: 婚禮不存在
      嘗試對不存在的婚禮連結 LINE
      Given no prior events
      When Admin sends ConnectLineOa on stream "wedding-999":
        """
        {
          "oaName": "王李婚禮小助手",
          "channelId": "1234567890",
          "weddingId": "wedding-999"
        }
        """
      Then the operation fails with: 婚禮不存在
