# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 建立接待帳號
  管理員為婚禮建立接待人員共用帳號

  @happy-path @happy-path
  Rule: 成功建立接待帳號
    管理員成功為婚禮建立新接待帳號

    Scenario: 成功建立接待帳號
      全新帳號名稱成功建立接待帳號
      Given no prior events
      When Admin sends CreateReceptionAccount on stream "account-001":
        """
        {
          "username": "reception-desk-1",
          "accountId": "account-001",
          "weddingId": "wedding-001"
        }
        """
      Then the ReceptionAccountCreated event is emitted with:
        """
        {
          "username": "reception-desk-1",
          "createdBy": "user-001",
          "weddingId": "wedding-001"
        }
        """

  @integrity-constraint @username-already-exists
  Rule: 帳號名稱已存在
    同一婚禮下已有相同帳號名稱時拒絕建立

    Scenario: 帳號名稱已存在
      同一婚禮下已有相同 username 的接待帳號
      Given the ReceptionAccountCreated event has occurred on stream "account-001":
        """
        {
          "username": "reception-desk-1",
          "createdBy": "user-001",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends CreateReceptionAccount on stream "account-001":
        """
        {
          "username": "reception-desk-1",
          "accountId": "account-002",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 帳號名稱已存在
