# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 建立婚禮
  管理員建立新的婚禮場次

  @happy-path @happy-path
  Rule: 成功建立婚禮
    管理員成功建立新的婚禮場次

    Scenario: 成功建立婚禮
      管理員輸入婚禮名稱、場地、地址與日期成功建立
      Given no prior events
      When Admin sends CreateWedding on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "weddingId": "wedding-001"
        }
        """
      Then the WeddingCreated event is emitted with:
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
