# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 客製謝卡
  管理員為個別賓客客製謝卡內容

  @happy-path @happy-path
  Rule: 成功客製謝卡
    婚禮存在時成功客製

    Scenario: 成功客製謝卡
      婚禮已建立，管理員為特定賓客客製謝卡
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      When Admin sends CustomizeThankYouCard on stream "wedding-001":
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "customContent": "親愛的王大明，特別感謝您遠道而來！"
        }
        """
      Then the ThankYouCardCustomized event is emitted with:
        """
        {
          "guestId": "guest-001",
          "customContent": "親愛的王大明，特別感謝您遠道而來！"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時拒絕操作

    Scenario: 婚禮不存在
      婚禮尚未建立，客製謝卡失敗
      Given no prior events
      When Admin sends CustomizeThankYouCard on stream "wedding-001":
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "customContent": "特別感謝！"
        }
        """
      Then the operation fails with: 婚禮不存在
