# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 覆寫禮俗警告
  管理員覆寫特定禮俗警告

  @happy-path @happy-path
  Rule: 成功覆寫禮俗警告
    婚禮已存在時成功覆寫

    Scenario: 成功覆寫禮俗警告
      婚禮已建立，管理員忽略特定禮俗警告
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
      When Admin sends DismissEtiquetteWarning on stream "wedding-001":
        """
        {
          "warningId": "warning-001",
          "weddingId": "wedding-001",
          "warningType": "gender-separation"
        }
        """
      Then the EtiquetteWarningDismissed event is emitted with:
        """
        {
          "warningId": "warning-001",
          "dismissedBy": "admin-001",
          "warningType": "gender-separation"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時回傳錯誤

    Scenario: 婚禮不存在
      嘗試對不存在的婚禮覆寫禮俗警告
      Given no prior events
      When Admin sends DismissEtiquetteWarning on stream "wedding-999":
        """
        {
          "warningId": "warning-001",
          "weddingId": "wedding-999",
          "warningType": "gender-separation"
        }
        """
      Then the operation fails with: 婚禮不存在
