# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 發放喜餅
  接待端登記賓客喜餅已發放

  @happy-path @happy-path
  Rule: 成功發放喜餅
    接待人員成功登記賓客喜餅已發放

    Scenario: 成功發放喜餅
      接待人員為賓客登記喜餅發放
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Receptionist sends DistributeCakeBox on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "cakeBoxTypeId": "cake-type-001"
        }
        """
      Then the CakeBoxDistributed event is emitted with:
        """
        {
          "weddingId": "wedding-001",
          "cakeBoxTypeId": "cake-type-001",
          "distributedBy": "receptionist-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    發放喜餅時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Receptionist sends DistributeCakeBox on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "cakeBoxTypeId": "cake-type-001"
        }
        """
      Then the operation fails with: 賓客不存在

  @condition @already-distributed
  Rule: 已發放喜餅
    喜餅已發放不可重複發放

    Scenario: 已發放喜餅
      賓客已領取喜餅
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the CakeBoxDistributed event has occurred on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "cakeBoxTypeId": "cake-type-001",
          "distributedBy": "receptionist-001"
        }
        """
      When Receptionist sends DistributeCakeBox on stream "guest-001":
        """
        {
          "weddingId": "wedding-001",
          "cakeBoxTypeId": "cake-type-002"
        }
        """
      Then the operation fails with: 喜餅已發放
