# language: zh-TW
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 帳號列表
  顯示所有教練帳號清單（權限管理頁），排除已刪除帳號

  @happy-path @happy-path
  Rule: 顯示帳號列表
    存在帳號時正確顯示列表

    Scenario: 顯示帳號列表
      兩個帳號存在，顯示兩筆紀錄
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": "U12",
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountCreated event has occurred on stream "acc-002":
        """
        {
          "name": "李教練",
          "remark": null,
          "username": "coach_li",
          "hashedPassword": "<<hashed>>"
        }
        """
      When the AccountList view is queried
      Then the view returns:
        """
        [
          {
            "name": "王教練",
            "remark": "U12",
            "username": "coach_wang",
            "accountId": "acc-001"
          },
          {
            "name": "李教練",
            "remark": null,
            "username": "coach_li",
            "accountId": "acc-002"
          }
        ]
        """

  @derivation @exclude-deleted-accounts
  Rule: 排除已刪除帳號
    已刪除帳號不顯示在列表中

    Scenario: 排除已刪除帳號
      帳號已刪除，列表中不顯示
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountCreated event has occurred on stream "acc-002":
        """
        {
          "name": "李教練",
          "remark": null,
          "username": "coach_li",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountDeleted event has occurred on stream "acc-002":
        """
        {}
        """
      When the AccountList view is queried
      Then the view returns:
        """
        [
          {
            "name": "王教練",
            "remark": null,
            "username": "coach_wang",
            "accountId": "acc-001"
          }
        ]
        """

    Scenario: 空列表
      尚無任何帳號時回傳空列表
      Given no prior events
      When the AccountList view is queried
      Then the view returns an empty list

Feature: 球員列表
  顯示球員清單，支援球隊篩選與姓名搜尋，排除已刪除球員

  @happy-path @happy-path
  Rule: 顯示球員列表
    存在球員時正確顯示列表

    Scenario: 顯示球員列表
      兩名球員存在，顯示兩筆紀錄
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerCreated event has occurred on stream "player-002":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "林大華",
          "battingHand": "left",
          "throwingHand": "left"
        }
        """
      When the PlayerList view is queried
      Then the view returns:
        """
        [
          {
            "height": 165,
            "teamId": "team-001",
            "weight": 55,
            "playerId": "player-001",
            "playerName": "陳小明",
            "battingHand": "right",
            "throwingHand": "right"
          },
          {
            "height": 170,
            "teamId": "team-001",
            "weight": 60,
            "playerId": "player-002",
            "playerName": "林大華",
            "battingHand": "left",
            "throwingHand": "left"
          }
        ]
        """

  @derivation @exclude-deleted-players
  Rule: 排除已刪除球員
    已刪除球員不顯示在列表中

    Scenario: 排除已刪除球員
      球員已刪除，列表中不顯示
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerCreated event has occurred on stream "player-002":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "林大華",
          "battingHand": "left",
          "throwingHand": "left"
        }
        """
      And the PlayerDeleted event has occurred on stream "player-002":
        """
        {}
        """
      When the PlayerList view is queried
      Then the view returns:
        """
        [
          {
            "height": 165,
            "teamId": "team-001",
            "weight": 55,
            "playerId": "player-001",
            "playerName": "陳小明",
            "battingHand": "right",
            "throwingHand": "right"
          }
        ]
        """

    Scenario: 空列表
      尚無任何球員時回傳空列表
      Given no prior events
      When the PlayerList view is queried
      Then the view returns an empty list

Feature: 練習歷史總覽
  歷史總覽：依日期與球員分組顯示練習 sessions，含投球數統計

  @happy-path @happy-path
  Rule: 顯示練習歷史
    存在練習時正確顯示歷史總覽

    Scenario: 顯示練習歷史
      一次練習含兩球，正確顯示投球數統計
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 125,
          "pitchType": "CU",
          "haaDegrees": -4.8,
          "vaaDegrees": -10.2,
          "gyroDegrees": 25,
          "trueSpinRpm": 2300,
          "sideVideoUrl": "https://example.com/side2.mp4",
          "totalSpinRpm": 2400,
          "frontVideoUrl": "https://example.com/front2.mp4",
          "sswVerticalCm": 42,
          "spinDirDegrees": 180,
          "spinEfficiency": 0.92,
          "sswHorizontalCm": -10,
          "verticalBreakCm": 42,
          "horizontalBreakCm": -10,
          "strikeZoneLocationXCm": -5,
          "strikeZoneLocationZCm": 65
        }
        """
      And the PracticeEnded event has occurred on stream "practice-001":
        """
        {}
        """
      When the PracticeHistory view is queried
      Then the view returns:
        """
        [
          {
            "status": "ended",
            "playerIds": [
              "player-001"
            ],
            "pitchCount": 2,
            "practiceId": "practice-001",
            "practiceItem": "投球訓練"
          }
        ]
        """

  @derivation @derivation
  Rule: 投影邏輯
    練習歷史投影邏輯，含進行中狀態與空列表

    Scenario: 練習進行中
      練習尚未結束時 status 為 in-progress
      Given the PracticeStarted event has occurred on stream "practice-002":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-002":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      When the PracticeHistory view is queried
      Then the view returns:
        """
        [
          {
            "status": "in-progress",
            "playerIds": [
              "player-001"
            ],
            "pitchCount": 1,
            "practiceId": "practice-002",
            "practiceItem": "投球訓練"
          }
        ]
        """

    Scenario: 空列表
      尚無練習時回傳空列表
      Given no prior events
      When the PracticeHistory view is queried
      Then the view returns an empty list

Feature: 練習投球清單
  顯示單次練習中所有投球紀錄的詳細數據，含收藏與刪除狀態

  @happy-path @happy-path
  Rule: 顯示投球清單
    存在投球紀錄時正確顯示清單

    Scenario: 顯示投球清單
      一球已收藏、一球未收藏，正確顯示收藏狀態
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 125,
          "pitchType": "CU",
          "haaDegrees": -4.8,
          "vaaDegrees": -10.2,
          "gyroDegrees": 25,
          "trueSpinRpm": 2300,
          "sideVideoUrl": "https://example.com/side2.mp4",
          "totalSpinRpm": 2400,
          "frontVideoUrl": "https://example.com/front2.mp4",
          "sswVerticalCm": 42,
          "spinDirDegrees": 180,
          "spinEfficiency": 0.92,
          "sswHorizontalCm": -10,
          "verticalBreakCm": 42,
          "horizontalBreakCm": -10,
          "strikeZoneLocationXCm": -5,
          "strikeZoneLocationZCm": 65
        }
        """
      And the PitchFavorited event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When the PracticePitches view is queried
      Then the view returns:
        """
        [
          {
            "ssw": 1.8,
            "speed": 130,
            "pitchId": "pitch-001",
            "playerId": "player-001",
            "spinAxis": 210,
            "spinRate": 2200,
            "isDeleted": false,
            "locationX": 0.1,
            "locationY": 0.5,
            "pitchType": "FF",
            "practiceId": "practice-001",
            "isFavorited": true,
            "sideVideoUrl": "https://example.com/side.mp4",
            "approachAngle": -5.2,
            "frontVideoUrl": "https://example.com/front.mp4",
            "verticalBreak": 38,
            "spinEfficiency": 95,
            "horizontalBreak": -15,
            "effectiveSpinRate": 2100
          },
          {
            "ssw": 1.9,
            "speed": 125,
            "pitchId": "pitch-002",
            "playerId": "player-001",
            "spinAxis": 180,
            "spinRate": 2400,
            "isDeleted": false,
            "locationX": -0.1,
            "locationY": 0.3,
            "pitchType": "CB",
            "practiceId": "practice-001",
            "isFavorited": false,
            "sideVideoUrl": "https://example.com/side2.mp4",
            "approachAngle": -4.8,
            "frontVideoUrl": "https://example.com/front2.mp4",
            "verticalBreak": 42,
            "spinEfficiency": 92,
            "horizontalBreak": -10,
            "effectiveSpinRate": 2300
          }
        ]
        """

  @derivation @derivation
  Rule: 投影邏輯
    投球清單投影邏輯，含刪除標記與空列表

    Scenario: 已刪除投球標記 isDeleted
      投球被刪除後 isDeleted 為 true
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchDeleted event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When the PracticePitches view is queried
      Then the view returns:
        """
        [
          {
            "ssw": 1.8,
            "speed": 130,
            "pitchId": "pitch-001",
            "playerId": "player-001",
            "spinAxis": 210,
            "spinRate": 2200,
            "isDeleted": true,
            "locationX": 0.1,
            "locationY": 0.5,
            "pitchType": "FF",
            "practiceId": "practice-001",
            "isFavorited": false,
            "sideVideoUrl": "https://example.com/side.mp4",
            "approachAngle": -5.2,
            "frontVideoUrl": "https://example.com/front.mp4",
            "verticalBreak": 38,
            "spinEfficiency": 95,
            "horizontalBreak": -15,
            "effectiveSpinRate": 2100
          }
        ]
        """

    Scenario: 空列表
      尚無投球紀錄時回傳空列表
      Given no prior events
      When the PracticePitches view is queried
      Then the view returns an empty list

Feature: 相機狀態列表
  顯示所有相機裝置的 ID、位置與連線狀態

  @happy-path @happy-path
  Rule: 顯示相機狀態
    存在相機裝置時正確顯示狀態列表

    Scenario: 顯示相機狀態
      兩台相機，一台連線、一台斷線
      Given the CameraRegistered event has occurred on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      And the CameraRegistered event has occurred on stream "camera-002":
        """
        {
          "deviceId": "CAM-B1",
          "position": "一壘側"
        }
        """
      And the CameraStatusUpdated event has occurred on stream "camera-002":
        """
        {
          "connectionStatus": "disconnected"
        }
        """
      When the CameraStatusList view is queried
      Then the view returns:
        """
        [
          {
            "cameraId": "camera-001",
            "deviceId": "CAM-A1",
            "position": "本壘後方",
            "connectionStatus": "connected"
          },
          {
            "cameraId": "camera-002",
            "deviceId": "CAM-B1",
            "position": "一壘側",
            "connectionStatus": "disconnected"
          }
        ]
        """

  @derivation @derivation
  Rule: 投影邏輯
    相機狀態列表投影邏輯，含空列表與預設連線狀態

    Scenario: 新註冊預設為 connected
      相機註冊後未收到狀態更新，預設連線狀態為 connected
      Given the CameraRegistered event has occurred on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      When the CameraStatusList view is queried
      Then the view returns:
        """
        [
          {
            "cameraId": "camera-001",
            "deviceId": "CAM-A1",
            "position": "本壘後方",
            "connectionStatus": "connected"
          }
        ]
        """

    Scenario: 空列表
      尚無相機裝置時回傳空列表
      Given no prior events
      When the CameraStatusList view is queried
      Then the view returns an empty list

Feature: 建立帳號
  教練建立新帳號（姓名、帳號、密碼、備註）

  @happy-path @happy-path
  Rule: 成功建立帳號
    提供有效資料時成功建立新帳號

    Scenario: 成功建立帳號
      新帳號名稱不重複，建立成功並產生 AccountCreated 事件
      Given no prior events
      When Coach sends CreateAccount on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": "U12 教練",
          "password": "pass1234",
          "username": "coach_wang"
        }
        """
      Then the AccountCreated event is emitted with:
        """
        {
          "name": "王教練",
          "remark": "U12 教練",
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """

  @integrity-constraint @username-already-exists
  Rule: 帳號名稱已存在
    同名帳號已存在時拒絕建立

    Scenario: 帳號名稱重複
      帳號 coach_wang 已被使用，拒絕建立
      Given the AccountList view returns:
        """
        {
          "items": [
            {
              "name": "舊教練",
              "username": "coach_wang",
              "accountId": "acc-existing"
            }
          ]
        }
        """
      When Coach sends CreateAccount on stream "acc-002":
        """
        {
          "name": "新教練",
          "remark": null,
          "password": "pass5678",
          "username": "coach_wang"
        }
        """
      Then the operation fails with: 帳號名稱已存在

Feature: 登入
  教練以帳號密碼登入系統

  @happy-path @happy-path
  Rule: 成功登入
    帳號存在且密碼正確時成功登入

    Scenario: 成功登入
      帳號存在且密碼正確，產生 CoachLoggedIn
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      When Anonymous sends Login on stream "acc-001":
        """
        {
          "password": "pass1234",
          "username": "coach_wang"
        }
        """
      Then the CoachLoggedIn event is emitted with:
        """
        {}
        """

  @not-found @account-not-found
  Rule: 帳號不存在
    帳號不存在時拒絕登入

    Scenario: 帳號不存在
      帳號 stream 無事件，拒絕登入
      Given no prior events
      When Anonymous sends Login on stream "acc-unknown":
        """
        {
          "password": "pass1234",
          "username": "nobody"
        }
        """
      Then the operation fails with: 帳號不存在

  @condition @account-deleted
  Rule: 帳號已刪除
    帳號已被刪除時拒絕登入

    Scenario: 帳號已刪除
      帳號已刪除，拒絕登入
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountDeleted event has occurred on stream "acc-001":
        """
        {}
        """
      When Anonymous sends Login on stream "acc-001":
        """
        {
          "password": "pass1234",
          "username": "coach_wang"
        }
        """
      Then the operation fails with: 帳號已刪除

Feature: 修改密碼
  教練修改帳號密碼

  @happy-path @happy-path
  Rule: 成功修改密碼
    帳號存在且未刪除時成功修改密碼

    Scenario: 成功修改密碼
      帳號存在，產生 AccountPasswordChanged
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      When Coach sends ChangePassword on stream "acc-001":
        """
        {
          "newPassword": "newpass5678"
        }
        """
      Then the AccountPasswordChanged event is emitted with:
        """
        {
          "hashedPassword": "<<new-hashed>>"
        }
        """

  @not-found @account-not-found
  Rule: 帳號不存在
    帳號不存在時拒絕修改

    Scenario: 帳號不存在
      帳號 stream 無事件，拒絕修改
      Given no prior events
      When Coach sends ChangePassword on stream "acc-unknown":
        """
        {
          "newPassword": "newpass5678"
        }
        """
      Then the operation fails with: 帳號不存在

  @condition @account-deleted
  Rule: 帳號已刪除
    帳號已被刪除時拒絕修改密碼

    Scenario: 帳號已刪除
      帳號已刪除，拒絕修改密碼
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountDeleted event has occurred on stream "acc-001":
        """
        {}
        """
      When Coach sends ChangePassword on stream "acc-001":
        """
        {
          "newPassword": "newpass5678"
        }
        """
      Then the operation fails with: 帳號已刪除

Feature: 修改備註
  教練修改帳號備註

  @happy-path @happy-path
  Rule: 成功修改備註
    帳號存在且未刪除時成功修改備註

    Scenario: 成功修改備註
      帳號存在，產生 AccountRemarkUpdated
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      When Coach sends UpdateRemark on stream "acc-001":
        """
        {
          "remark": "U15 教練"
        }
        """
      Then the AccountRemarkUpdated event is emitted with:
        """
        {
          "remark": "U15 教練"
        }
        """

  @not-found @account-not-found
  Rule: 帳號不存在
    帳號不存在時拒絕修改

    Scenario: 帳號不存在
      帳號 stream 無事件，拒絕修改備註
      Given no prior events
      When Coach sends UpdateRemark on stream "acc-unknown":
        """
        {
          "remark": "測試"
        }
        """
      Then the operation fails with: 帳號不存在

  @condition @account-deleted
  Rule: 帳號已刪除
    帳號已被刪除時拒絕修改備註

    Scenario: 帳號已刪除
      帳號已刪除，拒絕修改備註
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountDeleted event has occurred on stream "acc-001":
        """
        {}
        """
      When Coach sends UpdateRemark on stream "acc-001":
        """
        {
          "remark": "U15 教練"
        }
        """
      Then the operation fails with: 帳號已刪除

Feature: 刪除帳號
  教練刪除帳號

  @happy-path @happy-path
  Rule: 成功刪除帳號
    帳號存在且未刪除時成功刪除

    Scenario: 成功刪除帳號
      帳號存在且未刪除，產生 AccountDeleted
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      When Coach sends DeleteAccount on stream "acc-001":
        """
        {}
        """
      Then the AccountDeleted event is emitted with:
        """
        {}
        """

  @not-found @account-not-found
  Rule: 帳號不存在
    帳號不存在時拒絕刪除

    Scenario: 帳號不存在
      帳號 stream 無事件，拒絕刪除
      Given no prior events
      When Coach sends DeleteAccount on stream "acc-unknown":
        """
        {}
        """
      Then the operation fails with: 帳號不存在

  @condition @account-already-deleted
  Rule: 帳號已刪除
    帳號已被刪除時拒絕重複刪除

    Scenario: 帳號已刪除
      帳號已刪除，拒絕重複刪除
      Given the AccountCreated event has occurred on stream "acc-001":
        """
        {
          "name": "王教練",
          "remark": null,
          "username": "coach_wang",
          "hashedPassword": "<<hashed>>"
        }
        """
      And the AccountDeleted event has occurred on stream "acc-001":
        """
        {}
        """
      When Coach sends DeleteAccount on stream "acc-001":
        """
        {}
        """
      Then the operation fails with: 帳號已刪除

Feature: 建立隊伍
  教練建立新隊伍

  @happy-path @happy-path
  Rule: 成功建立隊伍
    提供隊伍名稱時成功建立

    Scenario: 成功建立隊伍
      建立新隊伍，產生 TeamCreated
      Given no prior events
      When Coach sends CreateTeam on stream "team-001":
        """
        {
          "teamName": "台北少棒隊"
        }
        """
      Then the TeamCreated event is emitted with:
        """
        {
          "teamName": "台北少棒隊"
        }
        """

Feature: 刪除隊伍
  教練刪除隊伍

  @happy-path @happy-path
  Rule: 成功刪除隊伍
    隊伍存在且未刪除時成功刪除

    Scenario: 成功刪除隊伍
      隊伍存在，產生 TeamDeleted
      Given the TeamCreated event has occurred on stream "team-001":
        """
        {
          "teamName": "台北少棒隊"
        }
        """
      When Coach sends DeleteTeam on stream "team-001":
        """
        {}
        """
      Then the TeamDeleted event is emitted with:
        """
        {}
        """

  @not-found @team-not-found
  Rule: 隊伍不存在
    隊伍不存在時拒絕刪除

    Scenario: 隊伍不存在
      隊伍 stream 無事件，拒絕刪除
      Given no prior events
      When Coach sends DeleteTeam on stream "team-unknown":
        """
        {}
        """
      Then the operation fails with: 隊伍不存在

  @condition @team-already-deleted
  Rule: 隊伍已刪除
    隊伍已被刪除時拒絕重複刪除

    Scenario: 隊伍已刪除
      隊伍已刪除，拒絕重複刪除
      Given the TeamCreated event has occurred on stream "team-001":
        """
        {
          "teamName": "台北少棒隊"
        }
        """
      And the TeamDeleted event has occurred on stream "team-001":
        """
        {}
        """
      When Coach sends DeleteTeam on stream "team-001":
        """
        {}
        """
      Then the operation fails with: 隊伍已刪除

Feature: 建立球員
  教練建立球員（姓名、隊伍、投打習慣、身高、體重）

  @happy-path @happy-path
  Rule: 成功建立球員
    提供有效資料時成功建立球員

    Scenario: 成功建立球員
      建立新球員，產生 PlayerCreated
      Given no prior events
      When Coach sends CreatePlayer on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      Then the PlayerCreated event is emitted with:
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """

Feature: 編輯球員
  教練編輯球員資料

  @happy-path @happy-path
  Rule: 成功編輯球員
    球員存在且未刪除時成功編輯

    Scenario: 成功編輯球員
      球員存在，產生 PlayerUpdated
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      When Coach sends UpdatePlayer on stream "player-001":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      Then the PlayerUpdated event is emitted with:
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """

  @not-found @player-not-found
  Rule: 球員不存在
    球員不存在時拒絕編輯

    Scenario: 球員不存在
      球員 stream 無事件，拒絕編輯
      Given no prior events
      When Coach sends UpdatePlayer on stream "player-unknown":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      Then the operation fails with: 球員不存在

  @condition @player-deleted
  Rule: 球員已刪除
    球員已刪除時拒絕編輯

    Scenario: 球員已刪除
      球員已刪除，拒絕編輯
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerDeleted event has occurred on stream "player-001":
        """
        {}
        """
      When Coach sends UpdatePlayer on stream "player-001":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      Then the operation fails with: 球員已刪除

Feature: 刪除球員
  教練刪除球員

  @happy-path @happy-path
  Rule: 成功刪除球員
    球員存在且未刪除時成功刪除

    Scenario: 成功刪除球員
      球員存在，產生 PlayerDeleted
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      When Coach sends DeletePlayer on stream "player-001":
        """
        {}
        """
      Then the PlayerDeleted event is emitted with:
        """
        {}
        """

  @not-found @player-not-found
  Rule: 球員不存在
    球員不存在時拒絕刪除

    Scenario: 球員不存在
      球員 stream 無事件，拒絕刪除
      Given no prior events
      When Coach sends DeletePlayer on stream "player-unknown":
        """
        {}
        """
      Then the operation fails with: 球員不存在

  @condition @player-already-deleted
  Rule: 球員已刪除
    球員已刪除時拒絕重複刪除

    Scenario: 球員已刪除
      球員已刪除，拒絕重複刪除
      Given the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerDeleted event has occurred on stream "player-001":
        """
        {}
        """
      When Coach sends DeletePlayer on stream "player-001":
        """
        {}
        """
      Then the operation fails with: 球員已刪除

Feature: 開啟練習
  教練選擇球員與練習項目，開啟投球練習

  @happy-path @happy-path
  Rule: 成功開啟練習
    選擇球員與項目後成功開啟練習

    Scenario: 成功開啟練習
      新練習建立，產生 PracticeStarted
      Given no prior events
      When Coach sends StartPractice on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      Then the PracticeStarted event is emitted with:
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """

Feature: 結束練習
  結束練習，不可重新開啟

  @happy-path @happy-path
  Rule: 成功結束練習
    練習進行中時成功結束

    Scenario: 成功結束練習
      練習進行中，結束練習，產生 PracticeEnded
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      When Coach sends EndPractice on stream "practice-001":
        """
        {}
        """
      Then the PracticeEnded event is emitted with:
        """
        {}
        """

  @condition @practice-already-ended
  Rule: 練習已結束
    練習已結束時拒絕重複結束

    Scenario: 練習已結束
      練習已結束，拒絕重複結束
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PracticeEnded event has occurred on stream "practice-001":
        """
        {}
        """
      When Coach sends EndPractice on stream "practice-001":
        """
        {}
        """
      Then the operation fails with: 練習已結束

Feature: 記錄投球
  系統自動擷取單球投球指標與影片（由 PitchDataTranslator 觸發）

  @happy-path @happy-path
  Rule: 成功記錄投球
    練習進行中時成功記錄投球數據

    Scenario: 成功記錄投球
      練習進行中，系統記錄一球數據，產生 PitchRecorded
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PendingPitchPair view returns:
        """
        {
          "bsaEventId": "evt-bsa-001",
          "practiceId": "practice-001",
          "receivedAt": "2026-05-19T10:00:00Z",
          "bt3dEventId": "evt-bt3d-001"
        }
        """
      When System sends RecordPitch on stream "practice-001":
        """
        {
          "ssw": 1.8,
          "speed": 130,
          "playerId": "player-001",
          "spinAxis": 210,
          "spinRate": 2200,
          "locationX": 0.1,
          "locationY": 0.5,
          "pitchType": "FF",
          "sideVideoUrl": "https://example.com/side.mp4",
          "approachAngle": -5.2,
          "frontVideoUrl": "https://example.com/front.mp4",
          "verticalBreak": 38,
          "spinEfficiency": 95,
          "horizontalBreak": -15,
          "effectiveSpinRate": 2100
        }
        """
      Then the PitchRecorded event is emitted with:
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """

  @condition @practice-ended
  Rule: 練習已結束
    練習已結束時拒絕記錄投球

    Scenario: 練習已結束
      練習已結束，拒絕記錄投球
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PracticeEnded event has occurred on stream "practice-001":
        """
        {}
        """
      And the PendingPitchPair view returns:
        """
        {
          "bsaEventId": "evt-bsa-001",
          "practiceId": "practice-001",
          "receivedAt": "2026-05-19T10:00:00Z",
          "bt3dEventId": "evt-bt3d-001"
        }
        """
      When System sends RecordPitch on stream "practice-001":
        """
        {
          "ssw": 1.8,
          "speed": 130,
          "playerId": "player-001",
          "spinAxis": 210,
          "spinRate": 2200,
          "locationX": 0.1,
          "locationY": 0.5,
          "pitchType": "FF",
          "sideVideoUrl": "https://example.com/side.mp4",
          "approachAngle": -5.2,
          "frontVideoUrl": "https://example.com/front.mp4",
          "verticalBreak": 38,
          "spinEfficiency": 95,
          "horizontalBreak": -15,
          "effectiveSpinRate": 2100
        }
        """
      Then the operation fails with: 練習已結束

Feature: 收藏單球
  教練收藏單球紀錄

  @happy-path @happy-path
  Rule: 成功收藏
    投球存在且未收藏時成功收藏

    Scenario: 成功收藏
      投球紀錄存在且未收藏，產生 PitchFavorited
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      When Coach sends FavoritePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the PitchFavorited event is emitted with:
        """
        {
          "pitchId": "pitch-001"
        }
        """

  @condition @pitch-already-favorited
  Rule: 投球已收藏
    投球已被收藏時拒絕重複收藏

    Scenario: 投球已收藏
      投球已收藏，拒絕重複收藏
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchFavorited event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When Coach sends FavoritePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the operation fails with: 投球已收藏

  @condition @pitch-deleted
  Rule: 投球已刪除
    投球已被刪除時拒絕收藏

    Scenario: 投球已刪除
      投球已刪除，拒絕收藏
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchDeleted event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When Coach sends FavoritePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the operation fails with: 投球已刪除

Feature: 取消收藏
  教練取消收藏單球紀錄

  @happy-path @happy-path
  Rule: 成功取消收藏
    投球已收藏時成功取消

    Scenario: 成功取消收藏
      投球已收藏，取消後產生 PitchUnfavorited
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchFavorited event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When Coach sends UnfavoritePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the PitchUnfavorited event is emitted with:
        """
        {
          "pitchId": "pitch-001"
        }
        """

  @condition @pitch-not-favorited
  Rule: 投球未收藏
    投球未被收藏時拒絕取消

    Scenario: 投球未收藏
      投球未收藏，拒絕取消收藏
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      When Coach sends UnfavoritePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the operation fails with: 投球未收藏

Feature: 刪除單球
  教練刪除單球紀錄

  @happy-path @happy-path
  Rule: 成功刪除單球
    投球存在且未刪除時成功刪除

    Scenario: 成功刪除單球
      投球紀錄存在，產生 PitchDeleted
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      When Coach sends DeletePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the PitchDeleted event is emitted with:
        """
        {
          "pitchId": "pitch-001"
        }
        """

  @condition @pitch-already-deleted
  Rule: 投球已刪除
    投球已被刪除時拒絕重複刪除

    Scenario: 投球已刪除
      投球已刪除，拒絕重複刪除
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PitchRecorded event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """
      And the PitchDeleted event has occurred on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      When Coach sends DeletePitch on stream "practice-001":
        """
        {
          "pitchId": "pitch-001"
        }
        """
      Then the operation fails with: 投球已刪除

Feature: 註冊相機
  相機裝置上線時自動註冊（由 CameraRegistrationTranslator 觸發）

  @happy-path @happy-path
  Rule: 成功註冊相機
    新裝置上線時成功註冊

    Scenario: 成功註冊相機
      新裝置上線，產生 CameraRegistered
      Given the external event arrives via CameraRegistrationTranslator on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      When System sends RegisterCamera on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      Then the CameraRegistered event is emitted with:
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """

  @integrity-constraint @camera-already-registered
  Rule: 裝置已註冊
    裝置已註冊時拒絕重複註冊

    Scenario: 裝置已註冊
      裝置已存在，拒絕重複註冊
      Given the CameraRegistered event has occurred on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      When System sends RegisterCamera on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      Then the operation fails with: 裝置已註冊

Feature: 更新相機狀態
  相機連線狀態變更（由 CameraStatusTranslator 觸發）

  @happy-path @happy-path
  Rule: 成功更新狀態
    相機已註冊時成功更新連線狀態

    Scenario: 成功更新狀態
      相機已註冊，更新為 disconnected，產生 CameraStatusUpdated
      Given the CameraRegistered event has occurred on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "position": "本壘後方"
        }
        """
      And the external event arrives via CameraStatusTranslator on stream "camera-001":
        """
        {
          "deviceId": "CAM-A1",
          "connectionStatus": "disconnected"
        }
        """
      When System sends UpdateCameraStatus on stream "camera-001":
        """
        {
          "connectionStatus": "disconnected"
        }
        """
      Then the CameraStatusUpdated event is emitted with:
        """
        {
          "connectionStatus": "disconnected"
        }
        """

  @not-found @camera-not-registered
  Rule: 相機未註冊
    相機未註冊時拒絕更新狀態

    Scenario: 相機未註冊
      相機 stream 無事件，拒絕更新
      Given no prior events
      When System sends UpdateCameraStatus on stream "camera-unknown":
        """
        {
          "connectionStatus": "disconnected"
        }
        """
      Then the operation fails with: 相機未註冊

Feature: 請求匯出
  教練請求匯出單次練習或全部歷史為 CSV

  @happy-path @happy-path-single
  Rule: 匯出單次練習
    匯出單次練習為 CSV

    Scenario: 匯出單次練習
      指定 practiceId 匯出單次練習，產生 ExportRequested
      Given no prior events
      When Coach sends RequestExport on stream "export-001":
        """
        {
          "exportType": "single-practice",
          "practiceId": "practice-001"
        }
        """
      Then the ExportRequested event is emitted with:
        """
        {
          "exportType": "single-practice",
          "practiceId": "practice-001"
        }
        """

  @happy-path @happy-path-all
  Rule: 匯出全部歷史
    匯出全部歷史為 CSV

    Scenario: 匯出全部歷史
      匯出全部歷史，practiceId 為 null，產生 ExportRequested
      Given no prior events
      When Coach sends RequestExport on stream "export-002":
        """
        {
          "exportType": "all-history",
          "practiceId": null
        }
        """
      Then the ExportRequested event is emitted with:
        """
        {
          "exportType": "all-history",
          "practiceId": null
        }
        """

  @field-validation @missing-practice-id-for-single
  Rule: 缺少練習 ID
    匯出單次練習時未提供 practiceId

    Scenario: 缺少練習 ID
      exportType 為 single-practice 但 practiceId 為 null，拒絕匯出
      Given no prior events
      When Coach sends RequestExport on stream "export-003":
        """
        {
          "exportType": "single-practice",
          "practiceId": null
        }
        """
      Then the operation fails with: 匯出單次練習時必須提供 practiceId

Feature: 球隊列表
  顯示所有隊伍與其球員數，排除已刪除隊伍，球員數會隨已刪除球員遞減

  @happy-path @happy-path
  Rule: 顯示球隊列表
    存在隊伍時正確顯示列表，並計算各隊球員數

    Scenario: 顯示球隊列表
      兩隊各有不同球員數,正確顯示 playerCount
      Given the TeamCreated event has occurred on stream "team-001":
        """
        {
          "teamName": "台北少棒隊"
        }
        """
      And the TeamCreated event has occurred on stream "team-002":
        """
        {
          "teamName": "台中少棒隊"
        }
        """
      And the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerCreated event has occurred on stream "player-002":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "林大華",
          "battingHand": "left",
          "throwingHand": "left"
        }
        """
      And the PlayerCreated event has occurred on stream "player-003":
        """
        {
          "height": 172,
          "teamId": "team-002",
          "weight": 62,
          "playerName": "黃志強",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      When the TeamList view is queried
      Then the view returns:
        """
        [
          {
            "teamId": "team-001",
            "teamName": "台北少棒隊",
            "playerCount": 2
          },
          {
            "teamId": "team-002",
            "teamName": "台中少棒隊",
            "playerCount": 1
          }
        ]
        """

  @derivation @exclude-deleted-and-decrement-count
  Rule: 排除已刪除隊伍並遞減球員數
    已刪除隊伍不顯示；已刪除球員不計入 playerCount

    Scenario: 排除已刪除隊伍與球員
      team-002 已刪除整筆消失;team-001 內 player-002 已刪除 playerCount 由 2 變 1
      Given the TeamCreated event has occurred on stream "team-001":
        """
        {
          "teamName": "台北少棒隊"
        }
        """
      And the TeamCreated event has occurred on stream "team-002":
        """
        {
          "teamName": "台中少棒隊"
        }
        """
      And the PlayerCreated event has occurred on stream "player-001":
        """
        {
          "height": 165,
          "teamId": "team-001",
          "weight": 55,
          "playerName": "陳小明",
          "battingHand": "right",
          "throwingHand": "right"
        }
        """
      And the PlayerCreated event has occurred on stream "player-002":
        """
        {
          "height": 170,
          "teamId": "team-001",
          "weight": 60,
          "playerName": "林大華",
          "battingHand": "left",
          "throwingHand": "left"
        }
        """
      And the PlayerDeleted event has occurred on stream "player-002":
        """
        {}
        """
      And the TeamDeleted event has occurred on stream "team-002":
        """
        {}
        """
      When the TeamList view is queried
      Then the view returns:
        """
        [
          {
            "teamId": "team-001",
            "teamName": "台北少棒隊",
            "playerCount": 1
          }
        ]
        """

    Scenario: 空列表
      尚無任何隊伍時回傳空列表
      Given no prior events
      When the TeamList view is queried
      Then the view returns an empty list

Feature: 接收 bt3d 軌跡資料
  bt3d-module 擷取的投球 3D 軌跡原始資料轉譯為內部事件（由 Bt3dTranslator 觸發）

  @happy-path @happy-path
  Rule: 成功接收 bt3d 資料
    練習進行中時成功接收 bt3d 軌跡原始資料

    Scenario: 成功接收
      練習進行中，接收 bt3d 3D 軌跡資料，產生 Bt3dDataReceived
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the external event arrives via Bt3dTranslator on stream "practice-001":
        """
        {
          "rawTraj": "..raw-3d-traj..",
          "trajEndTs": 1.2,
          "trajStartTs": 0.8,
          "pitchTrajXc0": 0.1,
          "pitchTrajXc1": -25.5,
          "pitchTrajXc2": 0.3,
          "pitchTrajYc0": 0.05,
          "pitchTrajYc1": 0.2,
          "pitchTrajYc2": -9.8,
          "pitchTrajZc0": 1.8,
          "pitchTrajZc1": -0.5,
          "pitchTrajZc2": -4.9,
          "rawTraj2dCam0": "..cam0-2d..",
          "rawTraj2dCam1": "..cam1-2d.."
        }
        """
      When System sends ReceiveBt3dData on stream "practice-001":
        """
        {
          "rawTraj": "..raw-3d-traj..",
          "trajEndTs": 1.2,
          "trajStartTs": 0.8,
          "pitchTrajXc0": 0.1,
          "pitchTrajXc1": -25.5,
          "pitchTrajXc2": 0.3,
          "pitchTrajYc0": 0.05,
          "pitchTrajYc1": 0.2,
          "pitchTrajYc2": -9.8,
          "pitchTrajZc0": 1.8,
          "pitchTrajZc1": -0.5,
          "pitchTrajZc2": -4.9,
          "rawTraj2dCam0": "..cam0-2d..",
          "rawTraj2dCam1": "..cam1-2d.."
        }
        """
      Then the Bt3dDataReceived event is emitted with:
        """
        {
          "rawTraj": "..raw-3d-traj..",
          "trajEndTs": 1.2,
          "trajStartTs": 0.8,
          "pitchTrajXc0": 0.1,
          "pitchTrajXc1": -25.5,
          "pitchTrajXc2": 0.3,
          "pitchTrajYc0": 0.05,
          "pitchTrajYc1": 0.2,
          "pitchTrajYc2": -9.8,
          "pitchTrajZc0": 1.8,
          "pitchTrajZc1": -0.5,
          "pitchTrajZc2": -4.9,
          "rawTraj2dCam0": "..cam0-2d..",
          "rawTraj2dCam1": "..cam1-2d.."
        }
        """

  @condition @practice-ended
  Rule: 練習已結束
    練習已結束時拒絕接收 bt3d 資料

    Scenario: 練習已結束
      練習已結束，拒絕接收 bt3d 資料
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PracticeEnded event has occurred on stream "practice-001":
        """
        {}
        """
      And the external event arrives via Bt3dTranslator on stream "practice-001":
        """
        {
          "rawTraj": "..raw-3d-traj..",
          "trajEndTs": 1.2,
          "trajStartTs": 0.8,
          "pitchTrajXc0": 0.1,
          "pitchTrajXc1": -25.5,
          "pitchTrajXc2": 0.3,
          "pitchTrajYc0": 0.05,
          "pitchTrajYc1": 0.2,
          "pitchTrajYc2": -9.8,
          "pitchTrajZc0": 1.8,
          "pitchTrajZc1": -0.5,
          "pitchTrajZc2": -4.9,
          "rawTraj2dCam0": "..cam0-2d..",
          "rawTraj2dCam1": "..cam1-2d.."
        }
        """
      When System sends ReceiveBt3dData on stream "practice-001":
        """
        {
          "rawTraj": "..raw-3d-traj..",
          "trajEndTs": 1.2,
          "trajStartTs": 0.8,
          "pitchTrajXc0": 0.1,
          "pitchTrajXc1": -25.5,
          "pitchTrajXc2": 0.3,
          "pitchTrajYc0": 0.05,
          "pitchTrajYc1": 0.2,
          "pitchTrajYc2": -9.8,
          "pitchTrajZc0": 1.8,
          "pitchTrajZc1": -0.5,
          "pitchTrajZc2": -4.9,
          "rawTraj2dCam0": "..cam0-2d..",
          "rawTraj2dCam1": "..cam1-2d.."
        }
        """
      Then the operation fails with: 練習已結束

Feature: 接收 bsa 旋轉資料
  bsa-module 擷取的旋轉原始資料轉譯為內部事件（由 BsaTranslator 觸發）

  @happy-path @happy-path
  Rule: 成功接收 bsa 資料
    練習進行中時成功接收 bsa 旋轉原始資料

    Scenario: 成功接收
      練習進行中，接收 bsa 旋轉資料，產生 BsaDataReceived
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the external event arrives via BsaTranslator on stream "practice-001":
        """
        {
          "rpm": 2200,
          "axisX": 0.15,
          "axisY": 0.85,
          "axisZ": -0.5,
          "spinDirHhmm": "11:30",
          "spinTiltHhmm": "2:15",
          "spinDirDegrees": 210,
          "spinTiltDegrees": 45
        }
        """
      When System sends ReceiveBsaData on stream "practice-001":
        """
        {
          "rpm": 2200,
          "axisX": 0.15,
          "axisY": 0.85,
          "axisZ": -0.5,
          "spinDirHhmm": "11:30",
          "spinTiltHhmm": "2:15",
          "spinDirDegrees": 210,
          "spinTiltDegrees": 45
        }
        """
      Then the BsaDataReceived event is emitted with:
        """
        {
          "rpm": 2200,
          "axisX": 0.15,
          "axisY": 0.85,
          "axisZ": -0.5,
          "spinDirHhmm": "11:30",
          "spinTiltHhmm": "2:15",
          "spinDirDegrees": 210,
          "spinTiltDegrees": 45
        }
        """

  @condition @practice-ended
  Rule: 練習已結束
    練習已結束時拒絕接收 bsa 資料

    Scenario: 練習已結束
      練習已結束，拒絕接收 bsa 資料
      Given the PracticeStarted event has occurred on stream "practice-001":
        """
        {
          "playerId": "player-001",
          "practiceItem": "投球訓練"
        }
        """
      And the PracticeEnded event has occurred on stream "practice-001":
        """
        {}
        """
      And the external event arrives via BsaTranslator on stream "practice-001":
        """
        {
          "rpm": 2200,
          "axisX": 0.15,
          "axisY": 0.85,
          "axisZ": -0.5,
          "spinDirHhmm": "11:30",
          "spinTiltHhmm": "2:15",
          "spinDirDegrees": 210,
          "spinTiltDegrees": 45
        }
        """
      When System sends ReceiveBsaData on stream "practice-001":
        """
        {
          "rpm": 2200,
          "axisX": 0.15,
          "axisY": 0.85,
          "axisZ": -0.5,
          "spinDirHhmm": "11:30",
          "spinTiltHhmm": "2:15",
          "spinDirDegrees": 210,
          "spinTiltDegrees": 45
        }
        """
      Then the operation fails with: 練習已結束

Feature: 投球融合處理
  監看 PendingPitchPair 視圖，當 bt3d + bsa 原始資料配對完成後融合計算投球指標（由 PitchFusionProcessor 觸發）

  @happy-path @happy-path
  Rule: 成功融合投球資料
    bt3d + bsa 配對完成後融合計算並記錄投球

    Scenario: 成功融合
      PendingPitchPair 配對完成，融合產生 PitchRecorded
      Given the PendingPitchPair view returns:
        """
        {
          "bsaEventId": "evt-bsa-001",
          "practiceId": "practice-001",
          "receivedAt": "2026-05-19T10:00:00Z",
          "bt3dEventId": "evt-bt3d-001"
        }
        """
      When System sends RecordPitch on stream "practice-001":
        """
        {
          "ssw": 1.8,
          "speed": 130,
          "playerId": "player-001",
          "spinAxis": 210,
          "spinRate": 2200,
          "locationX": 0.1,
          "locationY": 0.5,
          "pitchType": "FF",
          "sideVideoUrl": "https://example.com/side.mp4",
          "approachAngle": -5.2,
          "frontVideoUrl": "https://example.com/front.mp4",
          "verticalBreak": 38,
          "spinEfficiency": 95,
          "horizontalBreak": -15,
          "effectiveSpinRate": 2100
        }
        """
      Then the PitchRecorded event is emitted with:
        """
        {
          "playerId": "player-001",
          "speedKmh": 130,
          "pitchType": "FF",
          "haaDegrees": -5.2,
          "vaaDegrees": -8.5,
          "gyroDegrees": 15,
          "trueSpinRpm": 2100,
          "sideVideoUrl": "https://example.com/side.mp4",
          "totalSpinRpm": 2200,
          "frontVideoUrl": "https://example.com/front.mp4",
          "sswVerticalCm": 38,
          "spinDirDegrees": 210,
          "spinEfficiency": 0.95,
          "sswHorizontalCm": -15,
          "verticalBreakCm": 38,
          "horizontalBreakCm": -15,
          "strikeZoneLocationXCm": 5,
          "strikeZoneLocationZCm": 75
        }
        """

  @condition @condition
  Rule: 練習已結束
    練習已結束時拒絕融合

    Scenario: 練習已結束
      練習已結束，拒絕融合投球資料
      Given the PendingPitchPair view returns:
        """
        {
          "bsaEventId": "evt-bsa-001",
          "practiceId": "practice-001",
          "receivedAt": "2026-05-19T10:00:00Z",
          "bt3dEventId": "evt-bt3d-001"
        }
        """
      When System sends RecordPitch on stream "practice-001":
        """
        {
          "ssw": 1.8,
          "speed": 130,
          "playerId": "player-001",
          "spinAxis": 210,
          "spinRate": 2200,
          "locationX": 0.1,
          "locationY": 0.5,
          "pitchType": "FF",
          "sideVideoUrl": "https://example.com/side.mp4",
          "approachAngle": -5.2,
          "frontVideoUrl": "https://example.com/front.mp4",
          "verticalBreak": 38,
          "spinEfficiency": 95,
          "horizontalBreak": -15,
          "effectiveSpinRate": 2100
        }
        """
      Then the operation fails with: 練習已結束
