# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 批次匯入賓客
  管理員透過 Excel 檔案批次匯入賓客名單

  @happy-path @happy-path
  Rule: 成功批次匯入賓客
    管理員上傳合法 Excel 檔案並成功匯入

    Scenario: 成功批次匯入賓客
      管理員上傳合法 Excel 檔案
      Given no prior events
      When Admin sends ImportGuestsBatch on stream "guest-001":
        """
        {
          "fileName": "guests-2026.xlsx",
          "weddingId": "wedding-001"
        }
        """
      Then the GuestsBatchImported event is emitted with:
        """
        {
          "fileName": "guests-2026.xlsx",
          "weddingId": "wedding-001",
          "importedBy": "admin-001",
          "importedCount": 25
        }
        """

  @field-validation @invalid-file-format
  Rule: 檔案格式不正確
    上傳的檔案非支援的 Excel 格式時拒絕匯入

    Scenario: 檔案格式不正確
      上傳非 Excel 格式的檔案
      Given no prior events
      When Admin sends ImportGuestsBatch on stream "guest-001":
        """
        {
          "fileName": "guests.pdf",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 檔案格式不正確，僅支援 .xlsx 或 .xls 格式
