# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 覆寫 RSVP
  管理員手動覆寫賓客的 RSVP 回覆

  @happy-path @happy-path
  Rule: 成功覆寫 RSVP
    管理員成功覆寫賓客的出席狀態

    Scenario: 成功覆寫 RSVP
      管理員將出席狀態覆寫為缺席
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the RsvpSubmitted event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "attending": "attending",
          "weddingId": "wedding-001",
          "plusOneCount": 1,
          "needChildSeat": false
        }
        """
      When Admin sends OverrideRsvp on stream "guest-001":
        """
        {
          "reason": "賓客臨時通知無法出席",
          "attending": "absent"
        }
        """
      Then the RsvpOverridden event is emitted with:
        """
        {
          "reason": "賓客臨時通知無法出席",
          "attending": "absent",
          "overriddenBy": "admin-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    覆寫 RSVP 時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Admin sends OverrideRsvp on stream "guest-001":
        """
        {
          "reason": "測試覆寫",
          "attending": "declined"
        }
        """
      Then the operation fails with: 賓客不存在
