# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 登記禮金
  接待端登記賓客禮金金額

  @happy-path @happy-path
  Rule: 成功登記禮金
    接待人員成功登記賓客禮金

    Scenario: 成功登記禮金
      接待人員為賓客登記禮金金額
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Receptionist sends RecordGiftMoney on stream "guest-001":
        """
        {
          "amount": 3600,
          "weddingId": "wedding-001"
        }
        """
      Then the GiftMoneyRecorded event is emitted with:
        """
        {
          "amount": 3600,
          "weddingId": "wedding-001",
          "recordedBy": "receptionist-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    登記禮金時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Receptionist sends RecordGiftMoney on stream "guest-001":
        """
        {
          "amount": 3600,
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 賓客不存在
