# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 註冊管理員
  Anonymous 使用者完成管理員帳號註冊

  @happy-path @happy-path
  Rule: 成功註冊管理員
    全新使用者成功完成管理員帳號註冊

    Scenario: 成功註冊管理員
      全新 email 成功註冊管理員帳號
      Given no prior events
      When Anonymous sends RegisterAdmin on stream "user-001":
        """
        {
          "email": "admin@example.com",
          "userId": "user-001",
          "displayName": "王小明"
        }
        """
      Then the AdminRegistered event is emitted with:
        """
        {
          "email": "admin@example.com",
          "userId": "user-001",
          "displayName": "王小明"
        }
        """

  @integrity-constraint @email-already-registered
  Rule: Email 已被註冊
    email 已被其他管理員帳號使用時拒絕註冊

    Scenario: Email 已被註冊
      已有相同 email 的管理員帳號存在時註冊失敗
      Given the AdminRegistered event has occurred on stream "user-001":
        """
        {
          "email": "admin@example.com",
          "userId": "user-001",
          "displayName": "已存在的管理員"
        }
        """
      When Anonymous sends RegisterAdmin on stream "user-001":
        """
        {
          "email": "admin@example.com",
          "userId": "user-002",
          "displayName": "李小華"
        }
        """
      Then the operation fails with: 此電子郵件已被註冊
