# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 審核拒絕祝福
  管理員審核拒絕賓客提交的祝福留言

  @happy-path @happy-path
  Rule: 成功審核拒絕祝福
    已提交的祝福成功被拒絕

    Scenario: 成功審核拒絕祝福
      管理員審核拒絕已提交的祝福
      Given the BlessingSubmitted event has occurred on stream "blessing-001":
        """
        {
          "guestId": "guest-001",
          "message": "不當內容",
          "photoUrl": "https://example.com/bad.jpg",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends RejectBlessing on stream "blessing-001":
        """
        {
          "reason": "內容不適當"
        }
        """
      Then the BlessingRejected event is emitted with:
        """
        {
          "reason": "內容不適當",
          "rejectedBy": "admin-001"
        }
        """

  @not-found @blessing-not-found
  Rule: 祝福不存在
    拒絕不存在的祝福時回傳錯誤

    Scenario: 祝福不存在
      嘗試拒絕不存在的祝福
      Given no prior events
      When Admin sends RejectBlessing on stream "blessing-999":
        """
        {
          "reason": "內容不適當"
        }
        """
      Then the operation fails with: 祝福不存在

  @condition @already-reviewed
  Rule: 祝福已審核
    已審核過的祝福不可再次拒絕

    Scenario: 祝福已被拒絕
      嘗試對已拒絕的祝福再次拒絕
      Given the BlessingSubmitted event has occurred on stream "blessing-001":
        """
        {
          "guestId": "guest-001",
          "message": "不當內容",
          "photoUrl": "https://example.com/bad.jpg",
          "weddingId": "wedding-001"
        }
        """
      And the BlessingRejected event has occurred on stream "blessing-001":
        """
        {
          "reason": "先前已拒絕",
          "rejectedBy": "admin-002"
        }
        """
      When Admin sends RejectBlessing on stream "blessing-001":
        """
        {
          "reason": "內容不適當"
        }
        """
      Then the operation fails with: 祝福已審核
