# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 移除接待帳號
  管理員移除婚禮的接待人員帳號

  @happy-path @happy-path
  Rule: 成功移除接待帳號
    管理員成功移除既有接待帳號

    Scenario: 成功移除接待帳號
      接待帳號存在時成功移除
      Given the ReceptionAccountCreated event has occurred on stream "account-001":
        """
        {
          "username": "reception-desk-1",
          "createdBy": "user-001",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends RemoveReceptionAccount on stream "account-001":
        """
        {
          "accountId": "account-001",
          "weddingId": "wedding-001"
        }
        """
      Then the ReceptionAccountRemoved event is emitted with:
        """
        {
          "removedBy": "user-001",
          "weddingId": "wedding-001"
        }
        """

  @not-found @account-not-found
  Rule: 帳號不存在
    指定的接待帳號不存在時拒絕移除

    Scenario: 帳號不存在
      接待帳號不存在時移除失敗
      Given no prior events
      When Admin sends RemoveReceptionAccount on stream "account-999":
        """
        {
          "accountId": "account-999",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 接待帳號不存在
