# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 移除賓客
  管理員軟刪除賓客資料

  @happy-path @happy-path
  Rule: 成功移除賓客
    管理員成功軟刪除一位賓客

    Scenario: 成功移除賓客
      管理員移除一位既有賓客
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Admin sends RemoveGuest on stream "guest-001":
        """
        {}
        """
      Then the GuestRemoved event is emitted with:
        """
        {
          "removedBy": "admin-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    移除不存在的賓客時回傳錯誤

    Scenario: 賓客不存在
      移除尚未新增的賓客
      Given no prior events
      When Admin sends RemoveGuest on stream "guest-999":
        """
        {}
        """
      Then the operation fails with: 賓客不存在

  @condition @already-removed
  Rule: 賓客已移除
    移除已被軟刪除的賓客時回傳錯誤

    Scenario: 賓客已移除
      賓客已被軟刪除，再次移除失敗
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the GuestRemoved event has occurred on stream "guest-001":
        """
        {
          "removedBy": "admin-001"
        }
        """
      When Admin sends RemoveGuest on stream "guest-001":
        """
        {}
        """
      Then the operation fails with: 賓客已移除
