# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 移除桌次
  管理員移除一張桌次

  @happy-path @happy-path
  Rule: 成功移除桌次
    桌次存在且無賓客入座時成功移除

    Scenario: 成功移除桌次
      桌次存在且無人入座
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends RemoveTable on stream "table-001":
        """
        {
          "tableId": "table-001",
          "weddingId": "wedding-001"
        }
        """
      Then the TableRemoved event is emitted with:
        """
        {
          "weddingId": "wedding-001"
        }
        """

  @not-found @table-not-found
  Rule: 桌次不存在
    移除不存在的桌次時回傳錯誤

    Scenario: 桌次不存在
      嘗試移除不存在的桌次
      Given no prior events
      When Admin sends RemoveTable on stream "table-999":
        """
        {
          "tableId": "table-999",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 桌次不存在

  @condition @has-seated-guests
  Rule: 桌次上還有賓客
    桌次上仍有賓客入座時不允許移除

    Scenario: 桌次上還有賓客
      桌次上仍有賓客入座，移除被拒絕
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "seatNumber": 1
        }
        """
      When Admin sends RemoveTable on stream "table-001":
        """
        {
          "tableId": "table-001",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 桌次上還有賓客，無法移除
