# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 移除喜餅款式
  管理員移除既有喜餅款式

  @happy-path @happy-path
  Rule: 成功移除喜餅款式
    既有款式成功移除

    Scenario: 成功移除喜餅款式
      管理員移除既有喜餅款式
      Given the CakeBoxTypeAdded event has occurred on stream "cakeboxtype-001":
        """
        {
          "name": "經典禮盒",
          "isDefault": true,
          "weddingId": "wedding-001",
          "description": "傳統經典喜餅禮盒"
        }
        """
      When Admin sends RemoveCakeBoxType on stream "cakeboxtype-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the CakeBoxTypeRemoved event is emitted with:
        """
        {
          "weddingId": "wedding-001"
        }
        """

  @not-found @cake-box-type-not-found
  Rule: 喜餅款式不存在
    移除不存在的喜餅款式時回傳錯誤

    Scenario: 喜餅款式不存在
      嘗試移除不存在的喜餅款式
      Given no prior events
      When Admin sends RemoveCakeBoxType on stream "cakeboxtype-999":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 喜餅款式不存在
