# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 恢復賓客
  管理員恢復已軟刪除的賓客資料

  @happy-path @happy-path
  Rule: 成功恢復賓客
    管理員成功恢復已軟刪除的賓客

    Scenario: 成功恢復賓客
      賓客已被軟刪除，管理員恢復
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the GuestRemoved event has occurred on stream "guest-001":
        """
        {
          "removedBy": "admin-001"
        }
        """
      When Admin sends RestoreGuest on stream "guest-001":
        """
        {}
        """
      Then the GuestRestored event is emitted with:
        """
        {
          "restoredBy": "admin-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    恢復不存在的賓客時回傳錯誤

    Scenario: 賓客不存在
      恢復尚未新增的賓客
      Given no prior events
      When Admin sends RestoreGuest on stream "guest-999":
        """
        {}
        """
      Then the operation fails with: 賓客不存在

  @condition @not-removed
  Rule: 賓客未被移除
    恢復未被軟刪除的賓客時回傳錯誤

    Scenario: 賓客未被移除
      賓客尚未被軟刪除
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Admin sends RestoreGuest on stream "guest-001":
        """
        {}
        """
      Then the operation fails with: 賓客未被移除
