# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 安排座位
  管理員將賓客分配至指定桌次與座位

  @happy-path @happy-path
  Rule: 成功安排座位
    桌次存在且有空位時成功安排

    Scenario: 成功安排座位
      桌次存在且有空位，賓客成功入座
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends SeatGuest on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "tableId": "table-001",
          "seatNumber": 1
        }
        """
      Then the GuestSeated event is emitted with:
        """
        {
          "guestId": "guest-001",
          "seatNumber": 1
        }
        """

  @not-found @table-not-found
  Rule: 桌次不存在
    安排座位時桌次不存在

    Scenario: 桌次不存在
      嘗試在不存在的桌次安排座位
      Given no prior events
      When Admin sends SeatGuest on stream "table-999":
        """
        {
          "guestId": "guest-001",
          "tableId": "table-999",
          "seatNumber": 1
        }
        """
      Then the operation fails with: 桌次不存在

  @condition @table-full
  Rule: 桌次已滿
    桌次座位已全部被佔用時不允許再安排

    Scenario: 桌次已滿
      桌次 capacity 為 10 已滿
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "seatNumber": 1
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-002",
          "seatNumber": 2
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-003",
          "seatNumber": 3
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-004",
          "seatNumber": 4
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-005",
          "seatNumber": 5
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-006",
          "seatNumber": 6
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-007",
          "seatNumber": 7
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-008",
          "seatNumber": 8
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-009",
          "seatNumber": 9
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-010",
          "seatNumber": 10
        }
        """
      When Admin sends SeatGuest on stream "table-001":
        """
        {
          "guestId": "guest-011",
          "tableId": "table-001",
          "seatNumber": 11
        }
        """
      Then the operation fails with: 桌次已滿，無法再安排座位

  @integrity-constraint @guest-already-seated
  Rule: 賓客已有座位
    同一賓客已在此桌入座時不允許重複安排

    Scenario: 賓客已有座位
      賓客已在此桌入座，再次安排被拒絕
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "seatNumber": 1
        }
        """
      When Admin sends SeatGuest on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "tableId": "table-001",
          "seatNumber": 5
        }
        """
      Then the operation fails with: 賓客已有座位
