# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 發送替代感謝
  對未加 LINE 好友的賓客發送替代感謝

  @happy-path @happy-path
  Rule: 成功發送替代感謝
    婚禮存在時透過 Email 或連結發送替代感謝

    Scenario: 透過 Email 發送替代感謝
      管理員選擇 Email 管道發送替代感謝
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      When Admin sends SendThankYouFallback on stream "wedding-001":
        """
        {
          "channel": "email",
          "guestId": "guest-002",
          "weddingId": "wedding-001"
        }
        """
      Then the ThankYouFallbackSent event is emitted with:
        """
        {
          "sentAt": "2026-12-15T10:00:00.000Z",
          "channel": "email",
          "guestId": "guest-002"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時拒絕操作

    Scenario: 婚禮不存在
      婚禮尚未建立，發送替代感謝失敗
      Given no prior events
      When Admin sends SendThankYouFallback on stream "wedding-001":
        """
        {
          "channel": "email",
          "guestId": "guest-002",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 婚禮不存在
