# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 發送 RSVP 邀請
  管理員透過指定管道發送 RSVP 邀請連結給賓客

  @happy-path @happy-path
  Rule: 成功發送 RSVP 邀請
    管理員成功發送 RSVP 邀請

    Scenario: 透過 LINE 發送 RSVP 邀請
      管理員透過 LINE 管道發送 RSVP 邀請
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Admin sends SendRsvpInvitation on stream "guest-001":
        """
        {
          "channel": "line",
          "rsvpToken": "tok-abc123",
          "weddingId": "wedding-001"
        }
        """
      Then the RsvpInvitationSent event is emitted with:
        """
        {
          "channel": "line",
          "rsvpToken": "tok-abc123",
          "weddingId": "wedding-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    發送 RSVP 邀請給不存在的賓客時回傳錯誤

    Scenario: 賓客不存在
      發送 RSVP 邀請給尚未新增的賓客
      Given no prior events
      When Admin sends SendRsvpInvitation on stream "guest-999":
        """
        {
          "channel": "line",
          "rsvpToken": "tok-xyz000",
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 賓客不存在
