# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 群發感謝訊息
  婚禮後透過 LINE Bot 群發感謝訊息給已綁定賓客

  @happy-path @happy-path
  Rule: 成功群發感謝訊息
    婚禮存在且有已綁定 LINE 的賓客時成功

    Scenario: 成功群發感謝訊息
      婚禮已建立且有已綁定 LINE 的賓客
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      And the GuestLineBound event has occurred on stream "wedding-001":
        """
        {
          "guestId": "guest-001",
          "weddingId": "wedding-001",
          "lineUserId": "U1234567890abcdef"
        }
        """
      When Admin sends SendThankYouBatch on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the ThankYouBatchSent event is emitted with:
        """
        {
          "sentAt": "2026-12-15T10:00:00.000Z",
          "sentBy": "admin-001",
          "recipientCount": 50
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時拒絕操作

    Scenario: 婚禮不存在
      婚禮尚未建立，群發失敗
      Given no prior events
      When Admin sends SendThankYouBatch on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 婚禮不存在

  @condition @no-bound-guests
  Rule: 沒有已綁定 LINE 的賓客
    婚禮存在但無已綁定 LINE 的賓客時拒絕群發

    Scenario: 沒有已綁定 LINE 的賓客
      婚禮已建立但無賓客綁定 LINE
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      When Admin sends SendThankYouBatch on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 沒有已綁定 LINE 的賓客
