# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 設定謝卡範本
  管理員設定謝卡範本內容與圖片

  @happy-path @happy-path
  Rule: 成功設定謝卡範本
    婚禮存在時成功設定

    Scenario: 成功設定謝卡範本
      婚禮已建立，管理員設定謝卡範本
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      When Admin sends SetThankYouCardTemplate on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001",
          "templateContent": "感謝您的祝福，我們會永遠珍惜！",
          "templateImageUrl": "https://example.com/thankyou.jpg"
        }
        """
      Then the ThankYouCardTemplateSet event is emitted with:
        """
        {
          "templateContent": "感謝您的祝福，我們會永遠珍惜！",
          "templateImageUrl": "https://example.com/thankyou.jpg"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時拒絕操作

    Scenario: 婚禮不存在
      婚禮尚未建立，設定謝卡範本失敗
      Given no prior events
      When Admin sends SetThankYouCardTemplate on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001",
          "templateContent": "感謝您的祝福！",
          "templateImageUrl": "https://example.com/thankyou.jpg"
        }
        """
      Then the operation fails with: 婚禮不存在
