# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 軟刪除婚禮
  管理員軟刪除婚禮資料（可恢復）

  @happy-path @happy-path
  Rule: 成功軟刪除婚禮
    婚禮存在且未被刪除時成功

    Scenario: 成功軟刪除婚禮
      婚禮已建立且未被刪除
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      When Admin sends SoftDeleteWedding on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the WeddingSoftDeleted event is emitted with:
        """
        {
          "deletedBy": "admin-001"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時拒絕操作

    Scenario: 婚禮不存在
      婚禮尚未建立
      Given no prior events
      When Admin sends SoftDeleteWedding on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 婚禮不存在

  @condition @already-deleted
  Rule: 婚禮已軟刪除
    婚禮已被軟刪除時拒絕重複刪除

    Scenario: 婚禮已軟刪除
      婚禮已被軟刪除，再次刪除失敗
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-12-01T12:00:00.000Z",
          "title": "小明與小美的婚禮",
          "venue": "台北圓山飯店",
          "address": "台北市中山區中山北路四段1號",
          "adminId": "admin-001"
        }
        """
      And the WeddingSoftDeleted event has occurred on stream "wedding-001":
        """
        {
          "deletedBy": "admin-001"
        }
        """
      When Admin sends SoftDeleteWedding on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 婚禮已被刪除
