# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 提交 RSVP
  賓客透過 LIFF 提交出席回覆

  @happy-path @happy-path
  Rule: 成功提交 RSVP
    賓客成功提交出席回覆

    Scenario: 提交出席
      賓客提交確定出席的 RSVP
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Guest sends SubmitRsvp on stream "guest-001":
        """
        {
          "diet": "meat",
          "attending": "attending",
          "weddingId": "wedding-001",
          "plusOneCount": 1,
          "needChildSeat": false
        }
        """
      Then the RsvpSubmitted event is emitted with:
        """
        {
          "diet": "meat",
          "attending": "attending",
          "weddingId": "wedding-001",
          "plusOneCount": 1,
          "needChildSeat": false
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    提交 RSVP 時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Guest sends SubmitRsvp on stream "guest-001":
        """
        {
          "diet": "meat",
          "attending": "attending",
          "weddingId": "wedding-001",
          "plusOneCount": 0,
          "needChildSeat": false
        }
        """
      Then the operation fails with: 賓客不存在

  @condition @already-submitted
  Rule: 已提交過 RSVP
    賓客已提交過 RSVP 不可重複提交

    Scenario: 已提交過 RSVP
      賓客已提交過 RSVP
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the RsvpSubmitted event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "attending": "attending",
          "weddingId": "wedding-001",
          "plusOneCount": 0,
          "needChildSeat": false
        }
        """
      When Guest sends SubmitRsvp on stream "guest-001":
        """
        {
          "diet": "vegetarian",
          "attending": "declined",
          "weddingId": "wedding-001",
          "plusOneCount": 0,
          "needChildSeat": false
        }
        """
      Then the operation fails with: 已提交過 RSVP
