# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 提交祝福
  賓客透過 LIFF 提交祝福留言或照片

  @happy-path @happy-path
  Rule: 成功提交祝福
    賓客成功提交祝福留言

    Scenario: 成功提交祝福
      賓客提交祝福留言與照片
      Given no prior events
      When Guest sends SubmitBlessing on stream "blessing-001":
        """
        {
          "guestId": "guest-001",
          "message": "祝福新人百年好合！",
          "photoUrl": "https://example.com/photo.jpg",
          "weddingId": "wedding-001"
        }
        """
      Then the BlessingSubmitted event is emitted with:
        """
        {
          "guestId": "guest-001",
          "message": "祝福新人百年好合！",
          "photoUrl": "https://example.com/photo.jpg",
          "weddingId": "wedding-001"
        }
        """
