# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 取消座位
  管理員取消賓客的座位分配

  @happy-path @happy-path
  Rule: 成功取消座位
    桌次存在且賓客在此桌時成功取消

    Scenario: 成功取消座位
      賓客已在此桌入座，管理員成功取消
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      And the GuestSeated event has occurred on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "seatNumber": 3
        }
        """
      When Admin sends UnseatGuest on stream "table-001":
        """
        {
          "guestId": "guest-001",
          "tableId": "table-001"
        }
        """
      Then the GuestUnseated event is emitted with:
        """
        {
          "guestId": "guest-001"
        }
        """

  @not-found @table-not-found
  Rule: 桌次不存在
    取消座位時桌次不存在

    Scenario: 桌次不存在
      嘗試在不存在的桌次取消座位
      Given no prior events
      When Admin sends UnseatGuest on stream "table-999":
        """
        {
          "guestId": "guest-001",
          "tableId": "table-999"
        }
        """
      Then the operation fails with: 桌次不存在

  @not-found @guest-not-at-table
  Rule: 賓客不在此桌
    賓客未在此桌入座時回傳錯誤

    Scenario: 賓客不在此桌
      賓客未在此桌入座，取消被拒絕
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends UnseatGuest on stream "table-001":
        """
        {
          "guestId": "guest-999",
          "tableId": "table-001"
        }
        """
      Then the operation fails with: 賓客不在此桌
