# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更新賓客
  管理員更新既有賓客的資料

  @happy-path @happy-path
  Rule: 成功更新賓客
    管理員更新既有賓客資料

    Scenario: 成功更新賓客
      管理員更新賓客飲食需求
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "同事",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Admin sends UpdateGuest on stream "guest-001":
        """
        {
          "diet": "vegetarian",
          "name": "陳大明",
          "side": "bride",
          "notes": "改為素食",
          "contact": "0987654321",
          "category": "朋友",
          "needChildSeat": true
        }
        """
      Then the GuestUpdated event is emitted with:
        """
        {
          "diet": "vegetarian",
          "name": "陳大明",
          "side": "bride",
          "notes": "改為素食",
          "contact": "0987654321",
          "category": "朋友",
          "needChildSeat": true
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    更新不存在的賓客時回傳錯誤

    Scenario: 賓客不存在
      更新尚未新增的賓客
      Given no prior events
      When Admin sends UpdateGuest on stream "guest-999":
        """
        {
          "diet": "meat",
          "name": "不存在的人",
          "side": "groom",
          "notes": "",
          "contact": "0900000000",
          "category": "朋友",
          "needChildSeat": false
        }
        """
      Then the operation fails with: 賓客不存在
