# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更新桌次
  管理員更新既有桌次的名稱、座位數或位置

  @happy-path @happy-path
  Rule: 成功更新桌次
    桌次存在時成功更新

    Scenario: 成功更新桌次
      桌次已存在，管理員更新名稱與座位數
      Given the TableAdded event has occurred on stream "table-001":
        """
        {
          "capacity": 10,
          "positionX": 100,
          "positionY": 200,
          "tableName": "主桌",
          "weddingId": "wedding-001"
        }
        """
      When Admin sends UpdateTable on stream "table-001":
        """
        {
          "tableId": "table-001",
          "capacity": 12,
          "positionX": 150,
          "positionY": 250,
          "tableName": "貴賓桌"
        }
        """
      Then the TableUpdated event is emitted with:
        """
        {
          "capacity": 12,
          "positionX": 150,
          "positionY": 250,
          "tableName": "貴賓桌"
        }
        """

  @not-found @table-not-found
  Rule: 桌次不存在
    更新不存在的桌次時回傳錯誤

    Scenario: 桌次不存在
      嘗試更新不存在的桌次
      Given no prior events
      When Admin sends UpdateTable on stream "table-999":
        """
        {
          "tableId": "table-999",
          "capacity": 10,
          "positionX": 0,
          "positionY": 0,
          "tableName": "不存在的桌"
        }
        """
      Then the operation fails with: 桌次不存在
