# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更新禮俗設定
  管理員更新禮俗建議引擎的開關設定

  @happy-path @happy-path
  Rule: 成功更新禮俗設定
    婚禮已存在時成功更新

    Scenario: 成功更新禮俗設定
      婚禮已建立，管理員更新禮俗開關
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
      When Admin sends UpdateEtiquetteSettings on stream "wedding-001":
        """
        {
          "weddingId": "wedding-001",
          "elderNearMain": true,
          "conflictWarning": true,
          "genderSeparation": true,
          "mainTableNearStage": true,
          "sameCategoryTogether": false
        }
        """
      Then the EtiquetteSettingsUpdated event is emitted with:
        """
        {
          "elderNearMain": true,
          "conflictWarning": true,
          "genderSeparation": true,
          "mainTableNearStage": true,
          "sameCategoryTogether": false
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時回傳錯誤

    Scenario: 婚禮不存在
      嘗試對不存在的婚禮更新禮俗設定
      Given no prior events
      When Admin sends UpdateEtiquetteSettings on stream "wedding-999":
        """
        {
          "weddingId": "wedding-999",
          "elderNearMain": true,
          "conflictWarning": true,
          "genderSeparation": true,
          "mainTableNearStage": true,
          "sameCategoryTogether": false
        }
        """
      Then the operation fails with: 婚禮不存在
