# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更新喜餅款式
  管理員更新既有喜餅款式的名稱與說明

  @happy-path @happy-path
  Rule: 成功更新喜餅款式
    既有款式成功更新

    Scenario: 成功更新喜餅款式
      管理員更新既有喜餅款式
      Given the CakeBoxTypeAdded event has occurred on stream "cakeboxtype-001":
        """
        {
          "name": "經典禮盒",
          "isDefault": true,
          "weddingId": "wedding-001",
          "description": "傳統經典喜餅禮盒"
        }
        """
      When Admin sends UpdateCakeBoxType on stream "cakeboxtype-001":
        """
        {
          "name": "豪華禮盒",
          "description": "升級版豪華喜餅禮盒"
        }
        """
      Then the CakeBoxTypeUpdated event is emitted with:
        """
        {
          "name": "豪華禮盒",
          "description": "升級版豪華喜餅禮盒"
        }
        """

  @not-found @cake-box-type-not-found
  Rule: 喜餅款式不存在
    更新不存在的喜餅款式時回傳錯誤

    Scenario: 喜餅款式不存在
      嘗試更新不存在的喜餅款式
      Given no prior events
      When Admin sends UpdateCakeBoxType on stream "cakeboxtype-999":
        """
        {
          "name": "豪華禮盒",
          "description": "升級版豪華喜餅禮盒"
        }
        """
      Then the operation fails with: 喜餅款式不存在
