# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更正禮金
  接待端更正賓客禮金金額

  @happy-path @happy-path
  Rule: 成功更正禮金
    接待人員成功更正賓客禮金金額

    Scenario: 成功更正禮金
      接待人員更正賓客的禮金金額
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      And the GiftMoneyRecorded event has occurred on stream "guest-001":
        """
        {
          "amount": 3600,
          "weddingId": "wedding-001",
          "recordedBy": "receptionist-001"
        }
        """
      When Receptionist sends UpdateGiftMoney on stream "guest-001":
        """
        {
          "amount": 6000,
          "weddingId": "wedding-001"
        }
        """
      Then the GiftMoneyUpdated event is emitted with:
        """
        {
          "amount": 6000,
          "updatedBy": "receptionist-001",
          "weddingId": "wedding-001"
        }
        """

  @not-found @guest-not-found
  Rule: 賓客不存在
    更正禮金時賓客不存在

    Scenario: 賓客不存在
      該賓客 ID 不存在
      Given no prior events
      When Receptionist sends UpdateGiftMoney on stream "guest-001":
        """
        {
          "amount": 6000,
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 賓客不存在

  @condition @no-gift-recorded
  Rule: 尚未登記禮金
    尚未登記禮金不可更正

    Scenario: 尚未登記禮金
      賓客尚未登記禮金，無法更正
      Given the GuestAdded event has occurred on stream "guest-001":
        """
        {
          "diet": "meat",
          "name": "陳大明",
          "side": "groom",
          "notes": "",
          "contact": "0912345678",
          "category": "朋友",
          "weddingId": "wedding-001",
          "needChildSeat": false
        }
        """
      When Receptionist sends UpdateGiftMoney on stream "guest-001":
        """
        {
          "amount": 6000,
          "weddingId": "wedding-001"
        }
        """
      Then the operation fails with: 尚未登記禮金
