# language: en
# auto-generated by scripts/codegen/shared/gherkin.ts — do not edit by hand

Feature: 更新婚禮資訊
  管理員更新婚禮資訊（時間、地點、交通指引等）

  @happy-path @happy-path
  Rule: 成功更新婚禮資訊
    婚禮已存在時成功更新資訊

    Scenario: 成功更新婚禮資訊
      婚禮已建立，管理員更新時間、地點、交通指引
      Given the WeddingCreated event has occurred on stream "wedding-001":
        """
        {
          "date": "2026-10-10T12:00:00Z",
          "title": "王小明與李小美的婚禮",
          "venue": "台北君悅酒店",
          "address": "台北市信義區松壽路2號",
          "adminId": "admin-001"
        }
        """
      When Admin sends UpdateWeddingInfo on stream "wedding-001":
        """
        {
          "date": "2026-11-11T12:00:00Z",
          "venue": "台北晶華酒店",
          "address": "台北市中山區中山北路二段39巷3號",
          "mapLink": "https://maps.google.com/example",
          "weddingId": "wedding-001",
          "parkingInfo": "飯店地下停車場B2",
          "transportInfo": "捷運中山站步行5分鐘"
        }
        """
      Then the WeddingInfoUpdated event is emitted with:
        """
        {
          "date": "2026-11-11T12:00:00Z",
          "venue": "台北晶華酒店",
          "address": "台北市中山區中山北路二段39巷3號",
          "mapLink": "https://maps.google.com/example",
          "parkingInfo": "飯店地下停車場B2",
          "transportInfo": "捷運中山站步行5分鐘"
        }
        """

  @not-found @wedding-not-found
  Rule: 婚禮不存在
    指定的婚禮不存在時回傳錯誤

    Scenario: 婚禮不存在
      嘗試更新不存在的婚禮資訊
      Given no prior events
      When Admin sends UpdateWeddingInfo on stream "wedding-999":
        """
        {
          "date": "2026-11-11T12:00:00Z",
          "venue": "台北晶華酒店",
          "address": "台北市中山區中山北路二段39巷3號",
          "mapLink": "https://maps.google.com/example",
          "weddingId": "wedding-999",
          "parkingInfo": "飯店地下停車場B2",
          "transportInfo": "捷運中山站步行5分鐘"
        }
        """
      Then the operation fails with: 婚禮不存在
